// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: utils
// transcript fingerprint: sha256:62f04b1592fafab15be3a3f5d942bd2a1f95738cc115634c0a6fa98450d6ff59

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// pointer resolves an object key
#[test]
#[rustfmt::skip]
fn probe_ptr_key() {
    check("ptr-key", &["ptr"], b"/a\x0a{\"a\":1,\"b\":2}", 0, b"1");
}

// array index segment
#[test]
#[rustfmt::skip]
fn probe_ptr_array() {
    check("ptr-array", &["ptr"], b"/a/1\x0a{\"a\":[10,20,30]}", 0, b"20");
}

// empty pointer resolves the whole document
#[test]
#[rustfmt::skip]
fn probe_ptr_empty() {
    check("ptr-empty", &["ptr"], b"\x0a{\"a\":1}", 0, b"{\"a\":1}");
}

// a pointer to nothing yields `missing`
#[test]
#[rustfmt::skip]
fn probe_ptr_missing() {
    check("ptr-missing", &["ptr"], b"/x\x0a{\"a\":1}", 0, b"missing");
}

// GetPointer decodes ~1 as / CORRECTLY (only the Patch decoder is buggy)
#[test]
#[rustfmt::skip]
fn probe_ptr_esc_slash() {
    check("ptr-esc-slash", &["ptr"], b"/a~1b\x0a{\"a/b\":9}", 0, b"9");
}

// GetPointer decodes ~0 as ~ correctly
#[test]
#[rustfmt::skip]
fn probe_ptr_esc_tilde() {
    check("ptr-esc-tilde", &["ptr"], b"/a~0b\x0a{\"a~b\":9}", 0, b"9");
}

// a leading-zero array index is rejected -> missing
#[test]
#[rustfmt::skip]
fn probe_ptr_leading_zero() {
    check("ptr-leading-zero", &["ptr"], b"/00\x0a[7,8]", 0, b"missing");
}

// status=0 and the replaced document
#[test]
#[rustfmt::skip]
fn probe_patch_replace() {
    check("patch-replace", &["patch"], b"[{\"op\":\"replace\",\"path\":\"/x\",\"value\":9}]\x0a{\"x\":1}", 0, b"status=0;{\"x\":9}");
}

// remove drops the key
#[test]
#[rustfmt::skip]
fn probe_patch_remove() {
    check("patch-remove", &["patch"], b"[{\"op\":\"remove\",\"path\":\"/x\"}]\x0a{\"x\":1,\"y\":2}", 0, b"status=0;{\"y\":2}");
}

// add inserts a new key
#[test]
#[rustfmt::skip]
fn probe_patch_add() {
    check("patch-add", &["patch"], b"[{\"op\":\"add\",\"path\":\"/newkey\",\"value\":1}]\x0a{\"a\":0}", 0, b"status=0;{\"a\":0,\"newkey\":1}");
}

// `-` appends to an array
#[test]
#[rustfmt::skip]
fn probe_patch_add_append() {
    check("patch-add-append", &["patch"], b"[{\"op\":\"add\",\"path\":\"/arr/-\",\"value\":9}]\x0a{\"arr\":[1,2]}", 0, b"status=0;{\"arr\":[1,2,9]}");
}

// a numeric index inserts before that position
#[test]
#[rustfmt::skip]
fn probe_patch_add_index() {
    check("patch-add-index", &["patch"], b"[{\"op\":\"add\",\"path\":\"/arr/1\",\"value\":9}]\x0a{\"arr\":[1,2]}", 0, b"status=0;{\"arr\":[1,9,2]}");
}

// test succeeds -> status 0
#[test]
#[rustfmt::skip]
fn probe_patch_test_pass() {
    check("patch-test-pass", &["patch"], b"[{\"op\":\"test\",\"path\":\"/x\",\"value\":1}]\x0a{\"x\":1}", 0, b"status=0;{\"x\":1}");
}

// test fails -> status 1, document unchanged
#[test]
#[rustfmt::skip]
fn probe_patch_test_fail() {
    check("patch-test-fail", &["patch"], b"[{\"op\":\"test\",\"path\":\"/x\",\"value\":2}]\x0a{\"x\":1}", 0, b"status=1;{\"x\":1}");
}

// move detaches from `from` and adds at `path`
#[test]
#[rustfmt::skip]
fn probe_patch_move() {
    check("patch-move", &["patch"], b"[{\"op\":\"move\",\"from\":\"/a\",\"path\":\"/b\"}]\x0a{\"a\":5}", 0, b"status=0;{\"b\":5}");
}

// copy duplicates `from` to `path`
#[test]
#[rustfmt::skip]
fn probe_patch_copy() {
    check("patch-copy", &["patch"], b"[{\"op\":\"copy\",\"from\":\"/a\",\"path\":\"/b\"}]\x0a{\"a\":5}", 0, b"status=0;{\"a\":5,\"b\":5}");
}

// an empty path replaces the whole document
#[test]
#[rustfmt::skip]
fn probe_patch_replace_root() {
    check("patch-replace-root", &["patch"], b"[{\"op\":\"replace\",\"path\":\"\",\"value\":[1,2]}]\x0a{\"old\":1}", 0, b"status=0;[1,2]");
}

// an unknown op -> status 3 (INVALID), document unchanged
#[test]
#[rustfmt::skip]
fn probe_patch_malformed() {
    check("patch-malformed", &["patch"], b"[{\"op\":\"bogus\",\"path\":\"/x\"}]\x0a{\"x\":1}", 0, b"status=3;{\"x\":1}");
}

// null removes a key
#[test]
#[rustfmt::skip]
fn probe_merge_null() {
    check("merge-null", &["merge"], b"{\"a\":null}\x0a{\"a\":1,\"b\":2}", 0, b"{\"b\":2}");
}

// objects merge recursively
#[test]
#[rustfmt::skip]
fn probe_merge_recursive() {
    check("merge-recursive", &["merge"], b"{\"a\":{\"c\":3}}\x0a{\"a\":{\"b\":2}}", 0, b"{\"a\":{\"b\":2,\"c\":3}}");
}

// a scalar replaces
#[test]
#[rustfmt::skip]
fn probe_merge_scalar() {
    check("merge-scalar", &["merge"], b"{\"a\":5}\x0a{\"a\":1}", 0, b"{\"a\":5}");
}

// a non-object patch replaces the whole target
#[test]
#[rustfmt::skip]
fn probe_merge_array() {
    check("merge-array", &["merge"], b"[1,2]\x0a{\"a\":1}", 0, b"[1,2]");
}

// generate merge-patch: remove b (null), add c
#[test]
#[rustfmt::skip]
fn probe_genmerge_diff() {
    check("genmerge-diff", &["genmerge"], b"{\"a\":1,\"b\":2}\x0a{\"a\":1,\"c\":3}", 0, b"{\"b\":null,\"c\":3}");
}

// identical -> null
#[test]
#[rustfmt::skip]
fn probe_genmerge_same() {
    check("genmerge-same", &["genmerge"], b"{\"a\":1}\x0a{\"a\":1}", 0, b"null");
}

// generate patch: replace
#[test]
#[rustfmt::skip]
fn probe_genpatch_scalar() {
    check("genpatch-scalar", &["genpatch"], b"{\"a\":1}\x0a{\"a\":2}", 0, b"[{\"op\":\"replace\",\"path\":\"/a\",\"value\":2}]");
}

// generate patch: add
#[test]
#[rustfmt::skip]
fn probe_genpatch_add() {
    check("genpatch-add", &["genpatch"], b"{\"a\":1}\x0a{\"a\":1,\"b\":2}", 0, b"[{\"op\":\"add\",\"path\":\"/b\",\"value\":2}]");
}

// generate patch over an array element
#[test]
#[rustfmt::skip]
fn probe_genpatch_array() {
    check("genpatch-array", &["genpatch"], b"[1,2,3]\x0a[1,9,3]", 0, b"[{\"op\":\"replace\",\"path\":\"/1\",\"value\":9}]");
}

// immediate object keys sort
#[test]
#[rustfmt::skip]
fn probe_sort_keys() {
    check("sort-keys", &["sort"], b"{\"c\":3,\"a\":1,\"b\":2}", 0, b"{\"a\":1,\"b\":2,\"c\":3}");
}

// SortObject is NOT recursive: the nested object keeps z-before-y
#[test]
#[rustfmt::skip]
fn probe_sort_nonrecursive() {
    check("sort-nonrecursive", &["sort"], b"{\"b\":1,\"a\":{\"z\":1,\"y\":2}}", 0, b"{\"a\":{\"z\":1,\"y\":2},\"b\":1}");
}

// sorting an array is a no-op (no keys to sort at the top; not recursive)
#[test]
#[rustfmt::skip]
fn probe_sort_array_noop() {
    check("sort-array-noop", &["sort"], b"[{\"c\":1,\"a\":2}]", 0, b"[{\"c\":1,\"a\":2}]");
}

// default sort is case-INsensitive: a sorts before B
#[test]
#[rustfmt::skip]
fn probe_sort_ci_default() {
    check("sort-ci-default", &["sort"], b"{\"B\":1,\"a\":2}", 0, b"{\"a\":2,\"B\":1}");
}

// case-sensitive sort: uppercase B (0x42) sorts before a (0x61)
#[test]
#[rustfmt::skip]
fn probe_sort_cs() {
    check("sort-cs", &["sort-cs"], b"{\"B\":1,\"a\":2}", 0, b"{\"B\":1,\"a\":2}");
}
