// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-mutate-place
// transcript fingerprint: sha256:5c0931e4fe521e7f8278146d678ab8c00c1e9999b8a785ae0cb3d4b4461ab6c2

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// insert at index 0: the C sets array->child to the new node and repairs the first element's prev, which is also the last-item cache
#[test]
#[rustfmt::skip]
fn probe_place_ins_at_front() {
    check("place-ins-at-front", &["seq"], b"[10,20]\x0ains\x09\x090", 0, b"init=[10,20]|ins:r=1,got=-,key=-,sz=3,doc=[0,10,20]");
}

// insert in the middle -- the plain relink, neither end of the list
#[test]
#[rustfmt::skip]
fn probe_place_ins_middle() {
    check("place-ins-middle", &["seq"], b"[10,20,30]\x0ains\x09\x091", 0, b"init=[10,20,30]|ins:r=1,got=-,key=-,sz=4,doc=[10,1,20,30]");
}

// index == size: get_array_item answers NULL, so this is already the APPEND path, not an in-place insert
#[test]
#[rustfmt::skip]
fn probe_place_ins_at_end_index() {
    check("place-ins-at-end-index", &["seq"], b"[10,20]\x0ains\x09\x092", 0, b"init=[10,20]|ins:r=1,got=-,key=-,sz=3,doc=[10,20,2]");
}

// an index far past the end does NOT fail. cJSON_InsertItemInArray falls through to add_item_to_array and appends (probed; spikes/place_relink.c)
#[test]
#[rustfmt::skip]
fn probe_place_ins_past_end() {
    check("place-ins-past-end", &["seq"], b"[1,2]\x0ains\x09\x0999", 0, b"init=[1,2]|ins:r=1,got=-,key=-,sz=3,doc=[1,2,99]");
}

// insert into an empty array: the append path again, and the branch that starts a fresh list (item->prev = item)
#[test]
#[rustfmt::skip]
fn probe_place_ins_into_empty() {
    check("place-ins-into-empty", &["seq"], b"[]\x0ains\x09\x090", 0, b"init=[]|ins:r=1,got=-,key=-,sz=1,doc=[0]");
}

// which < 0 is the C's own guard -- false, document untouched, and the caller still owns the node it was handed
#[test]
#[rustfmt::skip]
fn probe_place_ins_negative() {
    check("place-ins-negative", &["seq"], b"[1,2]\x0ains\x09\x09-1", 0, b"init=[1,2]|ins:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// THE WITNESS: insert at the front rewrites the last-item cache, and only a later append reads it back (LESSONS #39). 99 must land at the END
#[test]
#[rustfmt::skip]
fn probe_place_ins_then_append() {
    check("place-ins-then-append", &["seq"], b"[10,20]\x0ains\x09\x090\x0aapp\x09\x0999", 0, b"init=[10,20]|ins:r=1,got=-,key=-,sz=3,doc=[0,10,20]|app:r=1,got=-,key=-,sz=4,doc=[0,10,20,99]");
}

// same witness for the append path of insert
#[test]
#[rustfmt::skip]
fn probe_place_ins_end_then_append() {
    check("place-ins-end-then-append", &["seq"], b"[10,20]\x0ains\x09\x092\x0aapp\x09\x0999", 0, b"init=[10,20]|ins:r=1,got=-,key=-,sz=3,doc=[10,20,2]|app:r=1,got=-,key=-,sz=4,doc=[10,20,2,99]");
}

// and for the fresh-list branch, where a wrong prev would make the next append the first element
#[test]
#[rustfmt::skip]
fn probe_place_ins_empty_then_append() {
    check("place-ins-empty-then-append", &["seq"], b"[]\x0ains\x09\x090\x0aapp\x09\x0999", 0, b"init=[]|ins:r=1,got=-,key=-,sz=1,doc=[0]|app:r=1,got=-,key=-,sz=2,doc=[0,99]");
}

// an unresolvable selector: no target, so the op is a recorded no-op on both sides
#[test]
#[rustfmt::skip]
fn probe_place_ins_missing_target() {
    check("place-ins-missing-target", &["seq"], b"[1,2]\x0ains\x09zz\x090", 0, b"init=[1,2]|ins:r=0,got=-,key=-,sz=-1,doc=[1,2]");
}

// a non-numeric index reads as 0 through the shared strtol rule before cJSON sees an int
#[test]
#[rustfmt::skip]
fn probe_place_ins_index_junk() {
    check("place-ins-index-junk", &["seq"], b"[1,2]\x0ains\x09\x09zz", 0, b"init=[1,2]|ins:r=1,got=-,key=-,sz=3,doc=[0,1,2]");
}

// 20 digits overflow long; strtol saturates and the driver clamps to INT_MAX, which is then the append path
#[test]
#[rustfmt::skip]
fn probe_place_ins_index_overflow() {
    check("place-ins-index-overflow", &["seq"], b"[1,2]\x0ains\x09\x0999999999999999999999", 0, b"init=[1,2]|ins:r=1,got=-,key=-,sz=3,doc=[1,2,2147483647]");
}

// the selector reaches one level down, so insert runs on a nested array and the rest of the document must come back untouched
#[test]
#[rustfmt::skip]
fn probe_place_ins_nested_array() {
    check("place-ins-nested-array", &["seq"], b"{\"a\":[1,2],\"b\":9}\x0ains\x09a\x091\x0aapp\x09a\x097", 0, b"init={\"a\":[1,2],\"b\":9}|ins:r=1,got=-,key=-,sz=3,doc={\"a\":[1,1,2],\"b\":9}|app:r=1,got=-,key=-,sz=4,doc={\"a\":[1,1,2,7],\"b\":9}");
}

// replace the first element, then append: the C has a special branch for parent->child == item and must still leave the cache right
#[test]
#[rustfmt::skip]
fn probe_place_rep_first() {
    check("place-rep-first", &["seq"], b"[10,20,30]\x0arep\x09\x090\x0aapp\x09\x0999", 0, b"init=[10,20,30]|rep:r=1,got=-,key=-,sz=3,doc=[0,20,30]|app:r=1,got=-,key=-,sz=4,doc=[0,20,30,99]");
}

// replace in the middle
#[test]
#[rustfmt::skip]
fn probe_place_rep_middle() {
    check("place-rep-middle", &["seq"], b"[10,20,30]\x0arep\x09\x091\x0aapp\x09\x0999", 0, b"init=[10,20,30]|rep:r=1,got=-,key=-,sz=3,doc=[10,1,30]|app:r=1,got=-,key=-,sz=4,doc=[10,1,30,99]");
}

// replace the LAST element -- the branch that writes parent->child->prev, i.e. the cache itself
#[test]
#[rustfmt::skip]
fn probe_place_rep_last() {
    check("place-rep-last", &["seq"], b"[10,20,30]\x0arep\x09\x092\x0aapp\x09\x0999", 0, b"init=[10,20,30]|rep:r=1,got=-,key=-,sz=3,doc=[10,20,2]|app:r=1,got=-,key=-,sz=4,doc=[10,20,2,99]");
}

// the only element: the C's `parent->child->prev == parent->child` self-referential case
#[test]
#[rustfmt::skip]
fn probe_place_rep_only_element() {
    check("place-rep-only-element", &["seq"], b"[42]\x0arep\x09\x090\x0aapp\x09\x0999", 0, b"init=[42]|rep:r=1,got=-,key=-,sz=1,doc=[0]|app:r=1,got=-,key=-,sz=2,doc=[0,99]");
}

// unlike insert, an out-of-range index IS a failure here: get_array_item answers NULL and ReplaceItemViaPointer rejects a NULL item
#[test]
#[rustfmt::skip]
fn probe_place_rep_out_of_range() {
    check("place-rep-out-of-range", &["seq"], b"[1]\x0arep\x09\x099", 0, b"init=[1]|rep:r=0,got=-,key=-,sz=1,doc=[1]");
}

// which < 0 guard
#[test]
#[rustfmt::skip]
fn probe_place_rep_negative() {
    check("place-rep-negative", &["seq"], b"[1,2]\x0arep\x09\x09-1", 0, b"init=[1,2]|rep:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// empty container: also the `parent->child == NULL` guard inside ReplaceItemViaPointer
#[test]
#[rustfmt::skip]
fn probe_place_rep_empty() {
    check("place-rep-empty", &["seq"], b"[]\x0arep\x09\x090", 0, b"init=[]|rep:r=0,got=-,key=-,sz=0,doc=[]");
}

// replace inside a nested array
#[test]
#[rustfmt::skip]
fn probe_place_rep_nested() {
    check("place-rep-nested", &["seq"], b"{\"a\":[1,2,3]}\x0arep\x09a\x091", 0, b"init={\"a\":[1,2,3]}|rep:r=1,got=-,key=-,sz=3,doc={\"a\":[1,1,3]}");
}

// the replacement takes the SLOT, not the end: order is a,b,c afterwards
#[test]
#[rustfmt::skip]
fn probe_place_ro_keeps_position() {
    check("place-ro-keeps-position", &["seq"], b"{\"a\":1,\"b\":2,\"c\":3}\x0aro\x09\x09b", 0, b"init={\"a\":1,\"b\":2,\"c\":3}|ro:r=1,got=-,key=-,sz=3,doc={\"a\":1,\"b\":1,\"c\":3}");
}

// replace_item_in_object strdups the LOOKUP string into the replacement's key before looking anything up, so a case-INsensitive replace of `a` rewrites the member's spelling to `a`. Probed, because it is the opposite of what the name suggests
#[test]
#[rustfmt::skip]
fn probe_place_ro_renames_key_case() {
    check("place-ro-renames-key-case", &["seq"], b"{\"A\":1}\x0aro\x09\x09a", 0, b"init={\"A\":1}|ro:r=1,got=-,key=-,sz=1,doc={\"a\":1}");
}

// the case-SENSITIVE twin finds nothing, so the document is untouched
#[test]
#[rustfmt::skip]
fn probe_place_ros_is_case_sensitive() {
    check("place-ros-is-case-sensitive", &["seq"], b"{\"A\":1}\x0aros\x09\x09a", 0, b"init={\"A\":1}|ros:r=0,got=-,key=-,sz=1,doc={\"A\":1}");
}

// duplicate keys resolve to the first match, like every other object walk in the C
#[test]
#[rustfmt::skip]
fn probe_place_ro_duplicate_first_wins() {
    check("place-ro-duplicate-first-wins", &["seq"], b"{\"k\":1,\"k\":2}\x0aro\x09\x09k", 0, b"init={\"k\":1,\"k\":2}|ro:r=1,got=-,key=-,sz=2,doc={\"k\":1,\"k\":2}");
}

// a missing key answers false. In the C the replacement has ALREADY been renamed at this point; the port consumes it by value, so there is no caller-visible node to have been mutated (DIVERGENCES.md, structural eliminations)
#[test]
#[rustfmt::skip]
fn probe_place_ro_missing_key() {
    check("place-ro-missing-key", &["seq"], b"{\"a\":1}\x0aro\x09\x09zz", 0, b"init={\"a\":1}|ro:r=0,got=-,key=-,sz=1,doc={\"a\":1}");
}

// an array parent: get_object_item compares ->string, and array children have none, so false
#[test]
#[rustfmt::skip]
fn probe_place_ro_array_parent() {
    check("place-ro-array-parent", &["seq"], b"[1,2]\x0aro\x09\x09k", 0, b"init=[1,2]|ro:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// empty object -- both the lookup and the child==NULL guard say no
#[test]
#[rustfmt::skip]
fn probe_place_ro_empty_object() {
    check("place-ro-empty-object", &["seq"], b"{}\x0aro\x09\x09k", 0, b"init={}|ro:r=0,got=-,key=-,sz=0,doc={}");
}

// a scalar parent: no child list to walk
#[test]
#[rustfmt::skip]
fn probe_place_ro_scalar_parent() {
    check("place-ro-scalar-parent", &["seq"], b"{\"a\":7}\x0aro\x09a\x09k", 0, b"init={\"a\":7}|ro:r=0,got=-,key=-,sz=0,doc={\"a\":7}");
}

// an EMPTY key is a findable key, unlike the NULL key the C would create by inserting into an object -- which is exactly why `ins` refuses object targets
#[test]
#[rustfmt::skip]
fn probe_place_ro_empty_key() {
    check("place-ro-empty-key", &["seq"], b"{\"\":1}\x0aros\x09\x09", 0, b"init={\"\":1}|ros:r=1,got=-,key=-,sz=1,doc={\"\":0}");
}

// replace one level down
#[test]
#[rustfmt::skip]
fn probe_place_ro_nested() {
    check("place-ro-nested", &["seq"], b"{\"o\":{\"x\":1,\"y\":2}}\x0aros\x09o\x09x", 0, b"init={\"o\":{\"x\":1,\"y\":2}}|ros:r=1,got=-,key=-,sz=2,doc={\"o\":{\"x\":1,\"y\":2}}");
}

// replace then detach the same key: the replacement must be findable under the key it was renamed to
#[test]
#[rustfmt::skip]
fn probe_place_ro_then_detach() {
    check("place-ro-then-detach", &["seq"], b"{\"a\":1,\"b\":2}\x0aro\x09\x09a\x0ados\x09\x09a", 0, b"init={\"a\":1,\"b\":2}|ro:r=1,got=-,key=-,sz=2,doc={\"a\":1,\"b\":2}|dos:r=1,got=1,key=1:a,sz=1,doc={\"b\":2}");
}

// five ops composing insert, replace, append and detach -- each step's descriptor is emitted, so a corruption at step 1 masked by step 4 is still visible
#[test]
#[rustfmt::skip]
fn probe_place_ins_rep_app_mix() {
    check("place-ins-rep-app-mix", &["seq"], b"[10,20,30]\x0ains\x09\x090\x0arep\x09\x092\x0aapp\x09\x097\x0ada\x09\x091\x0aapp\x09\x098", 0, b"init=[10,20,30]|ins:r=1,got=-,key=-,sz=4,doc=[0,10,20,30]|rep:r=1,got=-,key=-,sz=4,doc=[0,10,2,30]|app:r=1,got=-,key=-,sz=5,doc=[0,10,2,30,7]|da:r=1,got=10,key=-,sz=4,doc=[0,2,30,7]|app:r=1,got=-,key=-,sz=5,doc=[0,2,30,7,8]");
}

// replace the last, then remove around it, appending after each -- the cache is read back three times
#[test]
#[rustfmt::skip]
fn probe_place_rep_detach_append() {
    check("place-rep-detach-append", &["seq"], b"[1,2,3]\x0arep\x09\x092\x0ada\x09\x090\x0aapp\x09\x099\x0ada\x09\x092\x0aapp\x09\x098", 0, b"init=[1,2,3]|rep:r=1,got=-,key=-,sz=3,doc=[1,2,2]|da:r=1,got=1,key=-,sz=2,doc=[2,2]|app:r=1,got=-,key=-,sz=3,doc=[2,2,9]|da:r=1,got=9,key=-,sz=2,doc=[2,2]|app:r=1,got=-,key=-,sz=3,doc=[2,2,8]");
}

// insert then immediately replace the node just inserted
#[test]
#[rustfmt::skip]
fn probe_place_ins_then_rep_same_index() {
    check("place-ins-then-rep-same-index", &["seq"], b"[5]\x0ains\x09\x090\x0arep\x09\x090\x0aapp\x09\x099", 0, b"init=[5]|ins:r=1,got=-,key=-,sz=2,doc=[0,5]|rep:r=1,got=-,key=-,sz=2,doc=[0,5]|app:r=1,got=-,key=-,sz=3,doc=[0,5,9]");
}

// object placement and removal interleaved, including a case-insensitive detach of the renamed key
#[test]
#[rustfmt::skip]
fn probe_place_object_mix() {
    check("place-object-mix", &["seq"], b"{\"a\":1,\"b\":2}\x0aro\x09\x09a\x0axo\x09\x09b\x0aros\x09\x09a\x0ado\x09\x09A", 0, b"init={\"a\":1,\"b\":2}|ro:r=1,got=-,key=-,sz=2,doc={\"a\":1,\"b\":2}|xo:r=-,got=-,key=-,sz=1,doc={\"a\":1}|ros:r=1,got=-,key=-,sz=1,doc={\"a\":1}|do:r=1,got=1,key=1:a,sz=0,doc={}");
}

// twelve op lines with a cap of eight: the last four are ignored so the descriptor stays bounded whatever the fuzzer sends
#[test]
#[rustfmt::skip]
fn probe_place_max_ops_truncates() {
    check("place-max-ops-truncates", &["seq"], b"[1,2,3,4,5,6,7,8,9]\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091\x0aapp\x09\x091", 0, b"init=[1,2,3,4,5,6,7,8,9]|app:r=1,got=-,key=-,sz=10,doc=[1,2,3,4,5,6,7,8,9,1]|app:r=1,got=-,key=-,sz=11,doc=[1,2,3,4,5,6,7,8,9,1,1]|app:r=1,got=-,key=-,sz=12,doc=[1,2,3,4,5,6,7,8,9,1,1,1]|app:r=1,got=-,key=-,sz=13,doc=[1,2,3,4,5,6,7,8,9,1,1,1,1]|app:r=1,got=-,key=-,sz=14,doc=[1,2,3,4,5,6,7,8,9,1,1,1,1,1]|app:r=1,got=-,key=-,sz=15,doc=[1,2,3,4,5,6,7,8,9,1,1,1,1,1,1]|app:r=1,got=-,key=-,sz=16,doc=[1,2,3,4,5,6,7,8,9,1,1,1,1,1,1,1]|app:r=1,got=-,key=-,sz=17,doc=[1,2,3,4,5,6,7,8,9,1,1,1,1,1,1,1,1]");
}

// an unrecognized opcode records as `?` and changes nothing -- a fuzzed opcode cannot put arbitrary bytes into the descriptor
#[test]
#[rustfmt::skip]
fn probe_place_unknown_op() {
    check("place-unknown-op", &["seq"], b"[1,2]\x0a??\x09\x090\x0aapp\x09\x099", 0, b"init=[1,2]|?:r=-,got=-,key=-,sz=2,doc=[1,2]|app:r=1,got=-,key=-,sz=3,doc=[1,2,9]");
}

// a document and no program at all: just the initial state
#[test]
#[rustfmt::skip]
fn probe_place_no_ops() {
    check("place-no-ops", &["seq"], b"[1,2,3]", 0, b"init=[1,2,3]");
}

// an unparseable document is rc 1 with nothing on stdout -- there is no tree to mutate
#[test]
#[rustfmt::skip]
fn probe_place_unparseable() {
    check("place-unparseable", &["seq"], b"{oops\x0aapp\x09\x091", 1, b"");
}

// an interior NUL in the key: the C hands cJSON a C string, so the lookup is for `a` and the rename writes `a` -- everything after the NUL is invisible to it (LESSONS #29)
#[test]
#[rustfmt::skip]
fn probe_place_key_interior_nul() {
    check("place-key-interior-nul", &["seq"], b"{\"a\":1,\"b\":2}\x0aro\x09\x09a\x00zz\x0aapp\x09\x091", 0, b"init={\"a\":1,\"b\":2}|ro:r=1,got=-,key=-,sz=2,doc={\"a\":1,\"b\":2}");
}

// bytes 0x80-0xFF in a key: cJSON compares them verbatim with no UTF-8 validation, and so must the port
#[test]
#[rustfmt::skip]
fn probe_place_arg_high_bytes() {
    check("place-arg-high-bytes", &["seq"], b"{\"\xff\xfe\":1}\x0aros\x09\x09\xff\xfe", 0, b"init={\"\xff\xfe\":1}|ros:r=1,got=-,key=-,sz=1,doc={\"\xff\xfe\":2}");
}

// the C copies the op region into a NUL-terminated buffer and walks it with strchr, so everything past an interior NUL is invisible -- the second op never runs
#[test]
#[rustfmt::skip]
fn probe_place_ops_after_nul() {
    check("place-ops-after-nul", &["seq"], b"[1,2]\x0aapp\x09\x091\x00\x0ains\x09\x090", 0, b"init=[1,2]|app:r=1,got=-,key=-,sz=3,doc=[1,2,1]");
}
