// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-mutate-remove
// transcript fingerprint: sha256:1aa748346b58d3fe5428f8853930c6af40c3af7ff2d2b0b3dd1fb25a29a50e0a

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// detach the FIRST element, then append: the C's child->prev is its last-item cache, and this is where a corrupted one would surface. Single-shot modes report MATCH on the detach itself
#[test]
#[rustfmt::skip]
fn probe_seq_detach_first_then_append() {
    check("seq-detach-first-then-append", &["seq"], b"[10,20,30]\x0ada\x09\x090\x0aapp\x09\x0999\x0a", 0, b"init=[10,20,30]|da:r=1,got=10,key=-,sz=2,doc=[20,30]|app:r=1,got=-,key=-,sz=3,doc=[20,30,99]");
}

// same for the middle element -- the relink touches prev->next and next->prev
#[test]
#[rustfmt::skip]
fn probe_seq_detach_middle_then_append() {
    check("seq-detach-middle-then-append", &["seq"], b"[10,20,30]\x0ada\x09\x091\x0aapp\x09\x0999\x0a", 0, b"init=[10,20,30]|da:r=1,got=20,key=-,sz=2,doc=[10,30]|app:r=1,got=-,key=-,sz=3,doc=[10,30,99]");
}

// same for the last: this is the branch that writes through parent->child->prev, the exact line MUTATION-API-SPIKE.md H1a reproduces a NULL write on
#[test]
#[rustfmt::skip]
fn probe_seq_detach_last_then_append() {
    check("seq-detach-last-then-append", &["seq"], b"[10,20,30]\x0ada\x09\x092\x0aapp\x09\x0999\x0a", 0, b"init=[10,20,30]|da:r=1,got=30,key=-,sz=2,doc=[10,20]|app:r=1,got=-,key=-,sz=3,doc=[10,20,99]");
}

// the single-element list: parent->child becomes NULL and the next append must start a fresh one
#[test]
#[rustfmt::skip]
fn probe_seq_detach_only_then_append() {
    check("seq-detach-only-then-append", &["seq"], b"[42]\x0ada\x09\x090\x0aapp\x09\x0999\x0a", 0, b"init=[42]|da:r=1,got=42,key=-,sz=0,doc=[]|app:r=1,got=-,key=-,sz=1,doc=[99]");
}

// empty the list entirely, then append -- the cache must not survive as a dangling pointer
#[test]
#[rustfmt::skip]
fn probe_seq_detach_all_then_append() {
    check("seq-detach-all-then-append", &["seq"], b"[1,2]\x0ada\x09\x090\x0ada\x09\x090\x0aapp\x09\x097\x0a", 0, b"init=[1,2]|da:r=1,got=1,key=-,sz=1,doc=[2]|da:r=1,got=2,key=-,sz=0,doc=[]|app:r=1,got=-,key=-,sz=1,doc=[7]");
}

// an empty array: get_array_item answers NULL, so DetachItemViaPointer's item==NULL guard returns NULL
#[test]
#[rustfmt::skip]
fn probe_seq_detach_array_empty() {
    check("seq-detach-array-empty", &["seq"], b"[]\x0ada\x09\x090\x0a", 0, b"init=[]|da:r=0,got=-,key=-,sz=0,doc=[]");
}

// which < 0 is DetachItemFromArray's OWN guard (cJSON.c:2248), returning before the lookup
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_negative() {
    check("seq-detach-index-negative", &["seq"], b"[1,2]\x0ada\x09\x09-1\x0a", 0, b"init=[1,2]|da:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// past the end: the child walk runs out and answers NULL
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_out_of_range() {
    check("seq-detach-index-out-of-range", &["seq"], b"[1,2]\x0ada\x09\x0999\x0a", 0, b"init=[1,2]|da:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// a non-numeric index reads as 0 on both sides before cJSON sees an int
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_junk() {
    check("seq-detach-index-junk", &["seq"], b"[1,2]\x0ada\x09\x09zz\x0a", 0, b"init=[1,2]|da:r=1,got=1,key=-,sz=1,doc=[2]");
}

// an index past INT_MAX saturates rather than wrapping -- a wraparound would turn it into a valid index
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_overflow_high() {
    check("seq-detach-index-overflow-high", &["seq"], b"[1,2]\x0ada\x09\x092147483648\x0a", 0, b"init=[1,2]|da:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// and past INT_MIN, which then hits the negative guard
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_overflow_low() {
    check("seq-detach-index-overflow-low", &["seq"], b"[1,2]\x0ada\x09\x09-2147483649\x0a", 0, b"init=[1,2]|da:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// strtol skips leading whitespace; both sides must
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_leading_space() {
    check("seq-detach-index-leading-space", &["seq"], b"[1,2,3]\x0ada\x09\x09  2\x0a", 0, b"init=[1,2,3]|da:r=1,got=3,key=-,sz=2,doc=[1,2]");
}

// an explicit + sign
#[test]
#[rustfmt::skip]
fn probe_seq_detach_index_plus() {
    check("seq-detach-index-plus", &["seq"], b"[1,2,3]\x0ada\x09\x09+1\x0a", 0, b"init=[1,2,3]|da:r=1,got=2,key=-,sz=2,doc=[1,3]");
}

// DetachItemFromArray on an OBJECT: get_array_item has NO type check, so index 0 takes the first MEMBER -- and the detached node keeps its key (key=1:a). This file has shipped the array-only reading wrong three times
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_by_index() {
    check("seq-detach-object-by-index", &["seq"], b"{\"a\":1,\"b\":2}\x0ada\x09\x090\x0a", 0, b"init={\"a\":1,\"b\":2}|da:r=1,got=1,key=1:a,sz=1,doc={\"b\":2}");
}

// and the object's list relinks the same way; the append is refused because the target is not an array
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_by_index_then_append() {
    check("seq-detach-object-by-index-then-append", &["seq"], b"{\"a\":1,\"b\":2}\x0ada\x09\x090\x0aapp\x09\x095\x0a", 0, b"init={\"a\":1,\"b\":2}|da:r=1,got=1,key=1:a,sz=1,doc={\"b\":2}|app:r=0,got=-,key=-,sz=1,doc={\"b\":2}");
}

// a scalar has no child, so both the detach and the delete are no-ops -- size stays 0
#[test]
#[rustfmt::skip]
fn probe_seq_detach_scalar_root() {
    check("seq-detach-scalar-root", &["seq"], b"7\x0ada\x09\x090\x0axa\x09\x090\x0a", 0, b"init=7|da:r=0,got=-,key=-,sz=0,doc=7|xa:r=-,got=-,key=-,sz=0,doc=7");
}

// cJSON_DetachItemFromObject is CASE-INSENSITIVE, so `k` finds `K`
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_ci_hit() {
    check("seq-detach-object-ci-hit", &["seq"], b"{\"K\":1}\x0ado\x09\x09k\x0a", 0, b"init={\"K\":1}|do:r=1,got=1,key=1:K,sz=0,doc={}");
}

// cJSON_DetachItemFromObjectCaseSensitive is not -- the same input answers NULL. The pair only differs here
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_cs_miss() {
    check("seq-detach-object-cs-miss", &["seq"], b"{\"K\":1}\x0ados\x09\x09k\x0a", 0, b"init={\"K\":1}|dos:r=0,got=-,key=-,sz=1,doc={\"K\":1}");
}

// case-sensitive against both spellings present: the first detach takes `k`, the second finds nothing
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_cs_hit() {
    check("seq-detach-object-cs-hit", &["seq"], b"{\"k\":1,\"K\":2}\x0ados\x09\x09k\x0ados\x09\x09k\x0a", 0, b"init={\"k\":1,\"K\":2}|dos:r=1,got=1,key=1:k,sz=1,doc={\"K\":2}|dos:r=0,got=-,key=-,sz=1,doc={\"K\":2}");
}

// duplicate keys resolve to the FIRST match, so detaching twice removes both in order and the third finds nothing
#[test]
#[rustfmt::skip]
fn probe_seq_detach_dupkey_twice() {
    check("seq-detach-dupkey-twice", &["seq"], b"{\"k\":1,\"k\":2}\x0ado\x09\x09k\x0ado\x09\x09k\x0ado\x09\x09k\x0a", 0, b"init={\"k\":1,\"k\":2}|do:r=1,got=1,key=1:k,sz=1,doc={\"k\":2}|do:r=1,got=2,key=1:k,sz=0,doc={}|do:r=0,got=-,key=-,sz=0,doc={}");
}

// get_object_item compares ->string and an array's children have none, so both spellings answer NULL on an array
#[test]
#[rustfmt::skip]
fn probe_seq_detach_object_on_array() {
    check("seq-detach-object-on-array", &["seq"], b"[1,2]\x0ado\x09\x09k\x0ados\x09\x09k\x0a", 0, b"init=[1,2]|do:r=0,got=-,key=-,sz=2,doc=[1,2]|dos:r=0,got=-,key=-,sz=2,doc=[1,2]");
}

// an EMPTY key is a real key (distinct from the NULL key an array child carries): the case-sensitive lookup finds it
#[test]
#[rustfmt::skip]
fn probe_seq_detach_empty_key() {
    check("seq-detach-empty-key", &["seq"], b"{\"\":1,\"a\":2}\x0ados\x09\x09\x0ado\x09\x09\x0a", 0, b"init={\"\":1,\"a\":2}|dos:r=1,got=1,key=0:,sz=1,doc={\"a\":2}|do:r=0,got=-,key=-,sz=1,doc={\"a\":2}");
}

// DeleteItemFromArray returns void, so the descriptor reads r=- and the effect shows in sz/doc. The fourth call is on an empty array
#[test]
#[rustfmt::skip]
fn probe_seq_delete_array_past_empty() {
    check("seq-delete-array-past-empty", &["seq"], b"[1,2,3]\x0axa\x09\x090\x0axa\x09\x090\x0axa\x09\x090\x0axa\x09\x090\x0a", 0, b"init=[1,2,3]|xa:r=-,got=-,key=-,sz=2,doc=[2,3]|xa:r=-,got=-,key=-,sz=1,doc=[3]|xa:r=-,got=-,key=-,sz=0,doc=[]|xa:r=-,got=-,key=-,sz=0,doc=[]");
}

// DeleteItemFromObject is case-INsensitive, matching its Detach twin
#[test]
#[rustfmt::skip]
fn probe_seq_delete_object_ci() {
    check("seq-delete-object-ci", &["seq"], b"{\"K\":1,\"b\":2}\x0axo\x09\x09k\x0a", 0, b"init={\"K\":1,\"b\":2}|xo:r=-,got=-,key=-,sz=1,doc={\"b\":2}");
}

// DeleteItemFromObjectCaseSensitive removes only the exact spelling
#[test]
#[rustfmt::skip]
fn probe_seq_delete_object_cs() {
    check("seq-delete-object-cs", &["seq"], b"{\"K\":1,\"k\":2}\x0axos\x09\x09k\x0a", 0, b"init={\"K\":1,\"k\":2}|xos:r=-,got=-,key=-,sz=1,doc={\"K\":1}");
}

// a missing key means cJSON_Delete(NULL), which is a documented no-op -- probed, because a crash here would be the obvious failure mode
#[test]
#[rustfmt::skip]
fn probe_seq_delete_missing_key() {
    check("seq-delete-missing-key", &["seq"], b"{\"a\":1}\x0axo\x09\x09zz\x0axos\x09\x09zz\x0a", 0, b"init={\"a\":1}|xo:r=-,got=-,key=-,sz=1,doc={\"a\":1}|xos:r=-,got=-,key=-,sz=1,doc={\"a\":1}");
}

// delete shifts the indices, so the following detach at the same index takes a different element
#[test]
#[rustfmt::skip]
fn probe_seq_delete_then_detach_same() {
    check("seq-delete-then-detach-same", &["seq"], b"[1,2,3]\x0axa\x09\x091\x0ada\x09\x091\x0a", 0, b"init=[1,2,3]|xa:r=-,got=-,key=-,sz=2,doc=[1,3]|da:r=1,got=3,key=-,sz=1,doc=[1]");
}

// the selector reaches a direct child of the root, so the removal surface is exercised on a NON-root container
#[test]
#[rustfmt::skip]
fn probe_seq_nested_object_detach() {
    check("seq-nested-object-detach", &["seq"], b"{\"o\":{\"x\":1,\"y\":2}}\x0ados\x09o\x09x\x0a", 0, b"init={\"o\":{\"x\":1,\"y\":2}}|dos:r=1,got=1,key=1:x,sz=1,doc={\"o\":{\"y\":2}}");
}

// the witness op on a nested array -- the relink and the cache are per container, not per document
#[test]
#[rustfmt::skip]
fn probe_seq_nested_array_detach_then_append() {
    check("seq-nested-array-detach-then-append", &["seq"], b"{\"arr\":[1,2,3]}\x0ada\x09arr\x091\x0aapp\x09arr\x099\x0a", 0, b"init={\"arr\":[1,2,3]}|da:r=1,got=2,key=-,sz=2,doc={\"arr\":[1,3]}|app:r=1,got=-,key=-,sz=3,doc={\"arr\":[1,3,9]}");
}

// an unresolvable selector leaves no target: every op is a no-op and sz reads -1, distinct from a target of size 0
#[test]
#[rustfmt::skip]
fn probe_seq_selector_missing() {
    check("seq-selector-missing", &["seq"], b"{\"a\":1}\x0ada\x09zz\x090\x0ado\x09zz\x09a\x0a", 0, b"init={\"a\":1}|da:r=0,got=-,key=-,sz=-1,doc={\"a\":1}|do:r=0,got=-,key=-,sz=-1,doc={\"a\":1}");
}

// a selector against an ARRAY root: GetObjectItemCaseSensitive answers NULL, so no target
#[test]
#[rustfmt::skip]
fn probe_seq_selector_on_array_root() {
    check("seq-selector-on-array-root", &["seq"], b"[1,2]\x0ada\x09a\x090\x0a", 0, b"init=[1,2]|da:r=0,got=-,key=-,sz=-1,doc=[1,2]");
}

// the selector uses the case-SENSITIVE lookup, so `a` misses `A` -- deliberately fixed so the op's own case flag is the only thing varying
#[test]
#[rustfmt::skip]
fn probe_seq_selector_is_case_sensitive() {
    check("seq-selector-is-case-sensitive", &["seq"], b"{\"A\":[1,2]}\x0ada\x09a\x090\x0ada\x09A\x090\x0a", 0, b"init={\"A\":[1,2]}|da:r=0,got=-,key=-,sz=-1,doc={\"A\":[1,2]}|da:r=1,got=1,key=-,sz=1,doc={\"A\":[2]}");
}

// the C would hang a child off the scalar 7 (scalar-parent-child); the driver refuses on BOTH sides so this module's ledger stays on the removal surface. r=0, sz unchanged
#[test]
#[rustfmt::skip]
fn probe_seq_app_scalar_refused() {
    check("seq-app-scalar-refused", &["seq"], b"{\"a\":7}\x0aapp\x09a\x095\x0a", 0, b"init={\"a\":7}|app:r=0,got=-,key=-,sz=0,doc={\"a\":7}");
}

// the C would give the object a NULL-keyed member printing as ""; same refusal, same reason
#[test]
#[rustfmt::skip]
fn probe_seq_app_object_refused() {
    check("seq-app-object-refused", &["seq"], b"{\"a\":1}\x0aapp\x09\x095\x0a", 0, b"init={\"a\":1}|app:r=0,got=-,key=-,sz=1,doc={\"a\":1}");
}

// the only accepted target: an array. The appended value is CreateNumber of the index field, so it also crosses the negative branch
#[test]
#[rustfmt::skip]
fn probe_seq_app_array_ok() {
    check("seq-app-array-ok", &["seq"], b"[1]\x0aapp\x09\x095\x0aapp\x09\x09-3\x0a", 0, b"init=[1]|app:r=1,got=-,key=-,sz=2,doc=[1,5]|app:r=1,got=-,key=-,sz=3,doc=[1,5,-3]");
}

// a document with no program: `init=` alone, and the document must come back untouched
#[test]
#[rustfmt::skip]
fn probe_seq_no_ops() {
    check("seq-no-ops", &["seq"], b"[10,20,30]\x0a", 0, b"init=[10,20,30]");
}

// an unrecognized opcode records a `?` step and changes nothing; the next op still runs
#[test]
#[rustfmt::skip]
fn probe_seq_unknown_opcode() {
    check("seq-unknown-opcode", &["seq"], b"[10,20,30]\x0anope\x09\x090\x0ada\x09\x090\x0a", 0, b"init=[10,20,30]|?:r=-,got=-,key=-,sz=3,doc=[10,20,30]|da:r=1,got=10,key=-,sz=2,doc=[20,30]");
}

// opcodes are compared with strcmp, so `DA` is not `da`
#[test]
#[rustfmt::skip]
fn probe_seq_opcode_case() {
    check("seq-opcode-case", &["seq"], b"[10,20,30]\x0aDA\x09\x090\x0a", 0, b"init=[10,20,30]|?:r=-,got=-,key=-,sz=3,doc=[10,20,30]");
}

// ten ops, eight executed: the cap bounds the descriptor whatever the fuzzer sends, and both sides must stop at the same step
#[test]
#[rustfmt::skip]
fn probe_seq_op_cap() {
    check("seq-op-cap", &["seq"], b"[1,2,3,4,5,6,7,8,9,0]\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0ada\x09\x090\x0a", 0, b"init=[1,2,3,4,5,6,7,8,9,0]|da:r=1,got=1,key=-,sz=9,doc=[2,3,4,5,6,7,8,9,0]|da:r=1,got=2,key=-,sz=8,doc=[3,4,5,6,7,8,9,0]|da:r=1,got=3,key=-,sz=7,doc=[4,5,6,7,8,9,0]|da:r=1,got=4,key=-,sz=6,doc=[5,6,7,8,9,0]|da:r=1,got=5,key=-,sz=5,doc=[6,7,8,9,0]|da:r=1,got=6,key=-,sz=4,doc=[7,8,9,0]|da:r=1,got=7,key=-,sz=3,doc=[8,9,0]|da:r=1,got=8,key=-,sz=2,doc=[9,0]");
}

// a line with no tabs, one tab, two tabs: every missing field reads as empty, so the index is 0 three times
#[test]
#[rustfmt::skip]
fn probe_seq_missing_fields() {
    check("seq-missing-fields", &["seq"], b"[1,2,3]\x0ada\x0ada\x09\x0ada\x09\x09\x0a", 0, b"init=[1,2,3]|da:r=1,got=1,key=-,sz=2,doc=[2,3]|da:r=1,got=2,key=-,sz=1,doc=[3]|da:r=1,got=3,key=-,sz=0,doc=[]");
}

// a blank line is a `?` step, not a terminator -- it consumes one of the eight slots
#[test]
#[rustfmt::skip]
fn probe_seq_blank_op_lines() {
    check("seq-blank-op-lines", &["seq"], b"[1,2,3]\x0a\x0a\x0ada\x09\x090\x0a", 0, b"init=[1,2,3]|?:r=-,got=-,key=-,sz=3,doc=[1,2,3]|?:r=-,got=-,key=-,sz=3,doc=[1,2,3]|da:r=1,got=1,key=-,sz=2,doc=[2,3]");
}

// the last op line need not end in a newline
#[test]
#[rustfmt::skip]
fn probe_seq_trailing_no_newline() {
    check("seq-trailing-no-newline", &["seq"], b"[1,2,3]\x0ada\x09\x090", 0, b"init=[1,2,3]|da:r=1,got=1,key=-,sz=2,doc=[2,3]");
}

// the C copies the op region into a NUL-terminated buffer, so everything past an interior NUL is invisible to it -- one step runs, not three (LESSONS #29). Needs stdin_b64
#[test]
#[rustfmt::skip]
fn probe_seq_nul_truncates_ops() {
    check("seq-nul-truncates-ops", &["seq"], b"[1,2,3]\x0ada\x09\x090\x0a\x00xa\x09\x090\x0axa\x09\x090\x0a", 0, b"init=[1,2,3]|da:r=1,got=1,key=-,sz=2,doc=[2,3]");
}

// a non-ASCII key: cJSON compares bytes with strcmp and does no UTF-8 validation, so the raw bytes must match end to end
#[test]
#[rustfmt::skip]
fn probe_seq_high_bytes_in_key() {
    check("seq-high-bytes-in-key", &["seq"], b"{\"\xc3\xbf\":1}\x0ados\x09\x09\xc3\xbf\x0a", 0, b"init={\"\xc3\xbf\":1}|dos:r=1,got=1,key=2:\xc3\xbf,sz=0,doc={}");
}

// a key that is not valid UTF-8 at all: it cannot match, but both sides must fail to match it identically rather than one of them replacing bytes
#[test]
#[rustfmt::skip]
fn probe_seq_lone_high_byte_key() {
    check("seq-lone-high-byte-key", &["seq"], b"{\"a\":1}\x0ados\x09\x09\x80\xff\x0a", 0, b"init={\"a\":1}|dos:r=0,got=-,key=-,sz=1,doc={\"a\":1}");
}

// an unparseable document is rc 1 with nothing on stdout: unlike `set`, every op here needs a document to act on
#[test]
#[rustfmt::skip]
fn probe_seq_doc_unparseable() {
    check("seq-doc-unparseable", &["seq"], b"{oops\x0ada\x09\x090\x0a", 1, b"");
}

// an empty document line is also a parse failure
#[test]
#[rustfmt::skip]
fn probe_seq_doc_empty() {
    check("seq-doc-empty", &["seq"], b"\x0ada\x09\x090\x0a", 1, b"");
}

// six steps mixing every family across three containers; the descriptor after EVERY step is what makes a corruption that surfaces late visible at all
#[test]
#[rustfmt::skip]
fn probe_seq_interleaved() {
    check("seq-interleaved", &["seq"], b"{\"a\":1,\"b\":2,\"arr\":[10,20,30],\"o\":{\"x\":1}}\x0ada\x09\x090\x0aapp\x09arr\x0999\x0axo\x09\x09b\x0ados\x09o\x09x\x0ada\x09arr\x090\x0aapp\x09arr\x091\x0a", 0, b"init={\"a\":1,\"b\":2,\"arr\":[10,20,30],\"o\":{\"x\":1}}|da:r=1,got=1,key=1:a,sz=3,doc={\"b\":2,\"arr\":[10,20,30],\"o\":{\"x\":1}}|app:r=1,got=-,key=-,sz=4,doc={\"b\":2,\"arr\":[10,20,30,99],\"o\":{\"x\":1}}|xo:r=-,got=-,key=-,sz=2,doc={\"arr\":[10,20,30,99],\"o\":{\"x\":1}}|dos:r=1,got=1,key=1:x,sz=0,doc={\"arr\":[10,20,30,99],\"o\":{}}|da:r=1,got=10,key=-,sz=3,doc={\"arr\":[20,30,99],\"o\":{}}|app:r=1,got=-,key=-,sz=4,doc={\"arr\":[20,30,99,1],\"o\":{}}");
}
