// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-access
// transcript fingerprint: sha256:8ac28f75e16f53e8244fdc901605989734afafb7279581db5976ddd6a907b72a

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// cJSON_GetObjectItem is the CASE-INSENSITIVE lookup (cJSON.c: get_object_item(.., false)) -- that is its whole difference from GetObjectItemCaseSensitive, which the `query` mode already gates
#[test]
#[rustfmt::skip]
fn probe_access_key_case_insensitive() {
    check("access-key-case-insensitive", &["access"], b"ABC\x090\x0a{\"abc\":\"hi\"}", 0, b"has=1;kobj=\"hi\";kstr=hi;knum=nan;iarr=\"hi\";istr=hi;inum=nan");
}

// the exact-case key finds the same item, so case-insensitivity is a widening, not a replacement
#[test]
#[rustfmt::skip]
fn probe_access_key_exact() {
    check("access-key-exact", &["access"], b"abc\x090\x0a{\"abc\":\"hi\"}", 0, b"has=1;kobj=\"hi\";kstr=hi;knum=nan;iarr=\"hi\";istr=hi;inum=nan");
}

// absent key: HasObjectItem 0, GetObjectItem NULL, and both value accessors answer for NULL rather than crashing
#[test]
#[rustfmt::skip]
fn probe_access_key_missing() {
    check("access-key-missing", &["access"], b"zz\x090\x0a{\"abc\":\"hi\"}", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=\"hi\";istr=hi;inum=nan");
}

// THE QUIRK: cJSON_GetArrayItem is NOT array-only. cJSON.c:1869 walks `array->child` with no type check, so index 0 of an OBJECT returns its first VALUE. The port's get_array_item asserted array-only in its own doc comment and answered None; nothing disagreed for six gates because no mode called it
#[test]
#[rustfmt::skip]
fn probe_access_index_on_object_root() {
    check("access-index-on-object-root", &["access"], b"a\x090\x0a{\"a\":1}", 0, b"has=1;kobj=1;kstr=-;knum=3ff0000000000000;iarr=1;istr=-;inum=3ff0000000000000");
}

// the same child-list walk hands back a whole nested object, printed
#[test]
#[rustfmt::skip]
fn probe_access_index_nested_object() {
    check("access-index-nested-object", &["access"], b"k\x090\x0a{\"a\":{\"b\":1}}", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr={\"b\":1};istr=-;inum=nan");
}

// index 2 of an object is its third value -- insertion order, the C's sibling chain
#[test]
#[rustfmt::skip]
fn probe_access_index_object_third() {
    check("access-index-object-third", &["access"], b"k\x092\x0a{\"a\":1,\"b\":2,\"c\":3}", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=3;istr=-;inum=4008000000000000");
}

// the mirror case: an object lookup on an array root answers NULL, because get_object_item DOES type-check
#[test]
#[rustfmt::skip]
fn probe_access_key_on_array_root() {
    check("access-key-on-array-root", &["access"], b"k\x090\x0a[1,2]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=1;istr=-;inum=3ff0000000000000");
}

// ordinary array indexing, plus GetStringValue returning the element's text
#[test]
#[rustfmt::skip]
fn probe_access_index_in_range() {
    check("access-index-in-range", &["access"], b"k\x091\x0a[10,\"two\",true]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=\"two\";istr=two;inum=nan");
}

// walking off the end of the child list yields NULL, not UB
#[test]
#[rustfmt::skip]
fn probe_access_index_out_of_range() {
    check("access-index-out-of-range", &["access"], b"k\x099\x0a[10,\"two\",true]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// cJSON_GetArrayItem returns NULL for index < 0 BEFORE the cast to size_t -- the guard that stops a negative index becoming a huge unsigned one
#[test]
#[rustfmt::skip]
fn probe_access_index_negative() {
    check("access-index-negative", &["access"], b"k\x09-1\x0a[10,\"two\",true]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// INT_MIN: the negative guard holds at the extreme, where a naive abs() would overflow
#[test]
#[rustfmt::skip]
fn probe_access_index_int_min() {
    check("access-index-int-min", &["access"], b"k\x09-2147483648\x0a[1,2]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// INT_MAX walks the list to its end and answers NULL
#[test]
#[rustfmt::skip]
fn probe_access_index_int_max() {
    check("access-index-int-max", &["access"], b"k\x092147483647\x0a[1,2]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// DRIVER contract, not cJSON contract: strtol saturates to LONG_MAX and the driver clamps to INT_MAX. Pinned because both sides must normalize a fuzzed index identically before cJSON ever sees it
#[test]
#[rustfmt::skip]
fn probe_access_index_overflowing() {
    check("access-index-overflowing", &["access"], b"k\x0999999999999999999999\x0a[1,2]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// driver contract: strtol reads no digits and answers 0, so junk selects element 0 rather than failing
#[test]
#[rustfmt::skip]
fn probe_access_index_non_numeric() {
    check("access-index-non-numeric", &["access"], b"k\x09abc\x0a[1,2]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=1;istr=-;inum=3ff0000000000000");
}

// driver contract: strtol accepts a leading '+'
#[test]
#[rustfmt::skip]
fn probe_access_index_plus_signed() {
    check("access-index-plus-signed", &["access"], b"k\x09+1\x0a[7,8,9]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=8;istr=-;inum=4020000000000000");
}

// driver contract: strtol skips leading whitespace
#[test]
#[rustfmt::skip]
fn probe_access_index_space_padded() {
    check("access-index-space-padded", &["access"], b"k\x09  2\x0a[7,8,9]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=9;istr=-;inum=4022000000000000");
}

// a scalar has no child, so the child-list walk answers NULL -- the type check the C never makes is not needed here
#[test]
#[rustfmt::skip]
fn probe_access_scalar_root() {
    check("access-scalar-root", &["access"], b"k\x090\x0a42", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// same for a string root: no child list
#[test]
#[rustfmt::skip]
fn probe_access_string_root() {
    check("access-string-root", &["access"], b"k\x090\x0a\"hello\"", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// empty container, index 0 -> NULL
#[test]
#[rustfmt::skip]
fn probe_access_empty_array() {
    check("access-empty-array", &["access"], b"k\x090\x0a[]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// empty object, index 0 -> NULL
#[test]
#[rustfmt::skip]
fn probe_access_empty_object() {
    check("access-empty-object", &["access"], b"k\x090\x0a{}", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=-;istr=-;inum=nan");
}

// duplicate keys resolve to the FIRST match, matching the C's list walk (the parser accepts such a document, per the builder probes)
#[test]
#[rustfmt::skip]
fn probe_access_duplicate_keys() {
    check("access-duplicate-keys", &["access"], b"k\x090\x0a{\"k\":1,\"k\":2}", 0, b"has=1;kobj=1;kstr=-;knum=3ff0000000000000;iarr=1;istr=-;inum=3ff0000000000000");
}

// case-INSENSITIVE lookup for "K" returns the FIRST case-insensitive match -- the lowercase entry -- not the exactly-matching later one
#[test]
#[rustfmt::skip]
fn probe_access_duplicate_keys_case() {
    check("access-duplicate-keys-case", &["access"], b"K\x090\x0a{\"k\":1,\"K\":2}", 0, b"has=1;kobj=1;kstr=-;knum=3ff0000000000000;iarr=1;istr=-;inum=3ff0000000000000");
}

// the empty key is a real key and is findable
#[test]
#[rustfmt::skip]
fn probe_access_empty_key() {
    check("access-empty-key", &["access"], b"\x090\x0a{\"\":7}", 0, b"has=1;kobj=7;kstr=-;knum=401c000000000000;iarr=7;istr=-;inum=401c000000000000");
}

// valuestring is a C string: GetStringValue's result truncates at the interior NUL, and so does the printed form (LESSONS #29)
#[test]
#[rustfmt::skip]
fn probe_access_string_interior_nul() {
    check("access-string-interior-nul", &["access"], b"k\x090\x0a{\"k\":\"a\\u0000b\"}", 0, b"has=1;kobj=\"a\";kstr=a;knum=nan;iarr=\"a\";istr=a;inum=nan");
}

// GetNumberValue returns valuedouble; the descriptor encodes raw IEEE-754 bits so no float FORMATTER sits on the compared contract
#[test]
#[rustfmt::skip]
fn probe_access_number_fractional() {
    check("access-number-fractional", &["access"], b"n\x090\x0a{\"n\":3.5}", 0, b"has=1;kobj=3.5;kstr=-;knum=400c000000000000;iarr=3.5;istr=-;inum=400c000000000000");
}

// an integral number still answers as a double
#[test]
#[rustfmt::skip]
fn probe_access_number_integral() {
    check("access-number-integral", &["access"], b"n\x090\x0a{\"n\":42}", 0, b"has=1;kobj=42;kstr=-;knum=4045000000000000;iarr=42;istr=-;inum=4045000000000000");
}

// near-DBL_MAX survives to valuedouble bit-exactly
#[test]
#[rustfmt::skip]
fn probe_access_number_huge() {
    check("access-number-huge", &["access"], b"k\x090\x0a{\"k\":1e308}", 0, b"has=1;kobj=1e+308;kstr=-;knum=7fe1ccf385ebc8a0;iarr=1e+308;istr=-;inum=7fe1ccf385ebc8a0");
}

// -0.0 prints as "0" but carries the sign bit (8000000000000000). The bit encoding gates what the printed form cannot show
#[test]
#[rustfmt::skip]
fn probe_access_number_negative_zero() {
    check("access-number-negative-zero", &["access"], b"k\x090\x0a{\"k\":-0.0}", 0, b"has=1;kobj=0;kstr=-;knum=8000000000000000;iarr=0;istr=-;inum=8000000000000000");
}

// GetStringValue and GetNumberValue on a bool: NULL and NaN, the wrong-type answers
#[test]
#[rustfmt::skip]
fn probe_access_bool_value() {
    check("access-bool-value", &["access"], b"k\x090\x0a{\"k\":true}", 0, b"has=1;kobj=true;kstr=-;knum=nan;iarr=true;istr=-;inum=nan");
}

// a JSON null is a present key: has=1 with both typed accessors declining
#[test]
#[rustfmt::skip]
fn probe_access_null_value() {
    check("access-null-value", &["access"], b"k\x090\x0a{\"k\":null}", 0, b"has=1;kobj=null;kstr=-;knum=nan;iarr=null;istr=-;inum=nan");
}

// the child walk hands back a nested array, printed in full
#[test]
#[rustfmt::skip]
fn probe_access_deep_nest() {
    check("access-deep-nest", &["access"], b"k\x090\x0a[[[[1]]]]", 0, b"has=0;kobj=-;kstr=-;knum=nan;iarr=[[[1]]];istr=-;inum=nan");
}

// an unparseable document is rc=1 with empty stdout, matching every other parsing mode's contract
#[test]
#[rustfmt::skip]
fn probe_access_parse_failure() {
    check("access-parse-failure", &["access"], b"k\x090\x0a{bad", 1, b"");
}

// malformed driver input (no tab) is rc=2 usage, distinct from a parse failure
#[test]
#[rustfmt::skip]
fn probe_access_missing_tab() {
    check("access-missing-tab", &["access"], b"k0\x0a[1]", 2, b"");
}

// malformed driver input (no newline) is rc=2 usage
#[test]
#[rustfmt::skip]
fn probe_access_missing_newline() {
    check("access-missing-newline", &["access"], b"k\x090", 2, b"");
}
