// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-construct
// transcript fingerprint: sha256:7843e9b391240859e874dd1f1eb9187acc55312e49977991e503893ed475f2c8

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// EMPTY payload = the NULL element pointer, the only way to reach `numbers == NULL -> return NULL` in all four typed-array constructors. A Rust slice cannot be null, so this branch lives at the driver boundary
#[test]
#[rustfmt::skip]
fn probe_construct_empty_payload() {
    check("construct-empty-payload", &["construct"], b"3\x09k\x09x\x0a", 0, b"false=1;bool=2;raw=1:x;ints=-;flts=-;dbls=-;strs=-;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// count < 0 -> NULL in all four constructors (cJSON.c:2574). Distinct from count == 0, which returns an EMPTY array, not NULL
#[test]
#[rustfmt::skip]
fn probe_construct_count_negative() {
    check("construct-count-negative", &["construct"], b"-1\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=-;flts=-;dbls=-;strs=-;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// count == 0 with a non-NULL pointer: an empty array, and `a->child` stays NULL so the trailing prev-pointer fixup is skipped
#[test]
#[rustfmt::skip]
fn probe_construct_count_zero() {
    check("construct-count-zero", &["construct"], b"0\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=1;raw=1:x;ints=0;flts=0;dbls=0;strs=0;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// count clamped to what the payload holds. Passing count > the buffer is the out-of-bounds read these APIs cannot detect -- UB in the oracle, so it is deliberately unreachable from this mode
#[test]
#[rustfmt::skip]
fn probe_construct_count_past_avail() {
    check("construct-count-past-avail", &["construct"], b"99\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// a non-numeric count: strtol answers 0 and both sides must agree before cJSON ever sees an int
#[test]
#[rustfmt::skip]
fn probe_construct_count_junk() {
    check("construct-count-junk", &["construct"], b"zz\x09k\x09x\x0aabcd", 0, b"false=1;bool=1;raw=1:x;ints=0;flts=0;dbls=0;strs=0;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// 20 digits overflow long; strtol saturates and the driver clamps to INT_MAX, then the element count clamps again -- two clamps that must compose identically
#[test]
#[rustfmt::skip]
fn probe_construct_count_overflow() {
    check("construct-count-overflow", &["construct"], b"99999999999999999999\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// a leading '+' is accepted by strtol; Rust's own integer parse is not, so the driver has to normalize it explicitly
#[test]
#[rustfmt::skip]
fn probe_construct_count_plus() {
    check("construct-count-plus", &["construct"], b"+2\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// strtol skips leading whitespace
#[test]
#[rustfmt::skip]
fn probe_construct_count_leading_space() {
    check("construct-count-leading-space", &["construct"], b"   2\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// strtol stops at the first non-digit and keeps the prefix
#[test]
#[rustfmt::skip]
fn probe_construct_count_trailing_junk() {
    check("construct-count-trailing-junk", &["construct"], b"2xyz\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// cJSON_CreateIntArray: (double)int is exact, so valueint round-trips
#[test]
#[rustfmt::skip]
fn probe_construct_ints_basic() {
    check("construct-ints-basic", &["construct"], b"2\x09k\x09x\x0a\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|1,3ff0000000000000|2,4000000000000000;flts=2|0,0000000000000000|0,0000000000000000;dbls=1|0,0000000000000000;strs=2|1:\x01|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// INT_MIN and INT_MAX. Both widen to doubles the C's guards catch BEFORE the cast, so the saturation branch runs even for values needing no saturating. Probeable only because the arrays now read disjoint regions: this byte pair reinterpreted as an f64 is 0x7FFFFFFF80000000 -- a NaN -- so it used to diverge through a sibling array rather than through anything it tested
#[test]
#[rustfmt::skip]
fn probe_construct_ints_extremes() {
    check("construct-ints-extremes", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x80\xff\xff\xff\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|-2147483648,c1e0000000000000|2147483647,41dfffffffc00000;flts=2|0,0000000000000000|0,0000000000000000;dbls=1|0,0000000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// +inf >= INT_MAX and -inf <= (double)INT_MIN, so both saturate through the guards -- DEFINED behavior, unlike NaN, which fails both comparisons and falls into the undefined cast
#[test]
#[rustfmt::skip]
fn probe_construct_double_inf() {
    check("construct-double-inf", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0\x7f\x00\x00\x00\x00\x00\x00\xf0\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|0,0000000000000000|0,0000000000000000;dbls=2|2147483647,7ff0000000000000|-2147483648,fff0000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// -0.0: valueint 0, but the descriptor's raw bits carry the sign the printed form loses
#[test]
#[rustfmt::skip]
fn probe_construct_double_neg_zero() {
    check("construct-double-neg-zero", &["construct"], b"1\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=1|0,0000000000000000;flts=1|0,0000000000000000;dbls=1|0,8000000000000000;strs=1|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// 1e300 saturates valueint to INT_MAX while valuedouble keeps full range
#[test]
#[rustfmt::skip]
fn probe_construct_double_huge() {
    check("construct-double-huge", &["construct"], b"1\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x9cu\x00\x88<\xe47~\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=1|0,0000000000000000;flts=1|0,0000000000000000;dbls=1|2147483647,7e37e43c8800759c;strs=1|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// the >= INT_MAX guard is INCLUSIVE, so 2147483647.0 takes the guard rather than the cast; 2147483646.5 truncates toward zero
#[test]
#[rustfmt::skip]
fn probe_construct_double_int_boundary() {
    check("construct-double-int-boundary", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc0\xff\xff\xff\xdfA\x00\x00\xa0\xff\xff\xff\xdfA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|0,0000000000000000|0,0000000000000000;dbls=2|2147483647,41dfffffffc00000|2147483646,41dfffffffa00000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// the <= (double)INT_MIN guard is inclusive too
#[test]
#[rustfmt::skip]
fn probe_construct_double_neg_boundary() {
    check("construct-double-neg-boundary", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0\xc1\x00\x00\x10\x00\x00\x00\xe0\xc1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|0,0000000000000000|0,0000000000000000;dbls=2|-2147483648,c1e0000000000000|-2147483648,c1e0000000100000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// the smallest positive subnormal: valueint 0, valuedouble denormal
#[test]
#[rustfmt::skip]
fn probe_construct_double_subnormal() {
    check("construct-double-subnormal", &["construct"], b"1\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=1|0,0000000000000000;flts=1|0,0000000000000000;dbls=1|0,0000000000000001;strs=1|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// truncation toward zero on both signs (not floor)
#[test]
#[rustfmt::skip]
fn probe_construct_double_fraction() {
    check("construct-double-fraction", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0?\x00\x00\x00\x00\x00\x00\xe0\xbf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|0,0000000000000000|0,0000000000000000;dbls=2|0,3fe0000000000000|0,bfe0000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// cJSON_CreateFloatArray widens f32 to f64 before CreateNumber, so valuedouble is the exact widening, never a re-rounded decimal
#[test]
#[rustfmt::skip]
fn probe_construct_float_basic() {
    check("construct-float-basic", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc0?\x00\x00 \xc0", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|1,3ff8000000000000|-2,c004000000000000;dbls=1|0,0000000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// f32 infinities widen to f64 infinities and saturate the same way
#[test]
#[rustfmt::skip]
fn probe_construct_float_inf() {
    check("construct-float-inf", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x7f\x00\x00\x80\xff", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|2147483647,7ff0000000000000|-2147483648,fff0000000000000;dbls=1|0,0000000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// an f32 subnormal widens to a NORMAL f64 -- the widening has to be the hardware conversion on both sides, not a decimal round-trip
#[test]
#[rustfmt::skip]
fn probe_construct_float_subnormal() {
    check("construct-float-subnormal", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|0,36a0000000000000|0,36a0000000000000;dbls=1|0,0000000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// near +/-FLT_MAX: the widening is exact and valueint saturates both ways
#[test]
#[rustfmt::skip]
fn probe_construct_float_huge() {
    check("construct-float-huge", &["construct"], b"2\x09k\x09x\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9e\xc9\x7f\x7f\x9e\xc9\x7f\xff", 0, b"false=1;bool=2;raw=1:x;ints=2|0,0000000000000000|0,0000000000000000;flts=2|2147483647,47eff933c0000000|-2147483648,c7eff933c0000000;dbls=1|0,0000000000000000;strs=2|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// the payload split on NUL: fields are the maximal runs BETWEEN NULs, so a doubled NUL yields an EMPTY field, not a skipped one
#[test]
#[rustfmt::skip]
fn probe_construct_strings_split() {
    check("construct-strings-split", &["construct"], b"4\x09k\x09x\x0aab\x00cd\x00\x00ef", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=4|2:ab|2:cd|0:|2:ef;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// a trailing NUL yields a final EMPTY field -- the C's private copy is NUL-terminated so that field is a valid C string too
#[test]
#[rustfmt::skip]
fn probe_construct_strings_trailing_nul() {
    check("construct-strings-trailing-nul", &["construct"], b"3\x09k\x09x\x0aab\x00", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=2|2:ab|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// every byte a separator: five empty strings, and the int/float arrays see a zeroed group
#[test]
#[rustfmt::skip]
fn probe_construct_strings_all_nuls() {
    check("construct-strings-all-nuls", &["construct"], b"5\x09k\x09x\x0a\x00\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=5|0:|0:|0:|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// no separator at all: exactly ONE field, the whole payload
#[test]
#[rustfmt::skip]
fn probe_construct_strings_no_nul() {
    check("construct-strings-no-nul", &["construct"], b"2\x09k\x09x\x0aabcdefgh", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=1|2147483647,450ceccca0000000;dbls=0;strs=1|8:abcdefgh;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// an EMPTY raw prints as nothing at all, so the object renders {"k":} -- invalid JSON that cJSON emits happily. The C writes strlen+1 bytes then advances by strlen, so the value contributes zero bytes
#[test]
#[rustfmt::skip]
fn probe_construct_raw_empty() {
    check("construct-raw-empty", &["construct"], b"1\x09k\x09\x0aabcd", 0, b"false=1;bool=2;raw=0:;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":,\"k\":{},\"k\":[]}");
}

// raw content passes through VERBATIM with none of the escaping a String gets -- the whole point of a Raw node, and why the printer's Raw arm (previously unimplemented, on the reasoning that no mode could reach it) had to become real for this module
#[test]
#[rustfmt::skip]
fn probe_construct_raw_json() {
    check("construct-raw-json", &["construct"], b"1\x09k\x09{\"a\":1}\x0aabcd", 0, b"false=1;bool=2;raw=7:{\"a\":1};ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":{\"a\":1},\"k\":{},\"k\":[]}");
}

// raw passthrough does not validate: the printer emits structurally broken output without complaint. This is the escaping bypass, stated plainly
#[test]
#[rustfmt::skip]
fn probe_construct_raw_garbage() {
    check("construct-raw-garbage", &["construct"], b"1\x09k\x09}{not json\x0aabcd", 0, b"false=1;bool=2;raw=10:}{not json;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":}{not json,\"k\":{},\"k\":[]}");
}

// quotes and backslashes inside a Raw are NOT escaped, unlike a String
#[test]
#[rustfmt::skip]
fn probe_construct_raw_quotes() {
    check("construct-raw-quotes", &["construct"], b"1\x09k\x09has \"quotes\" and \\ backslash\x0aabcd", 0, b"false=1;bool=2;raw=28:has \"quotes\" and \\ backslash;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":has \"quotes\" and \\ backslash,\"k\":{},\"k\":[]}");
}

// an empty key is accepted (only a NULL key is refused), giving five entries all keyed ""
#[test]
#[rustfmt::skip]
fn probe_construct_key_empty() {
    check("construct-key-empty", &["construct"], b"1\x09\x09x\x0aabcd", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"\":true,\"\":false,\"\":x,\"\":{},\"\":[]}");
}

// all five Add*ToObject calls use the SAME key: cJSON APPENDS a duplicate key rather than replacing it, so one input covers both paths
#[test]
#[rustfmt::skip]
fn probe_construct_dupkey_appends() {
    check("construct-dupkey-appends", &["construct"], b"1\x09same\x09x\x0aabcd", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"same\":true,\"same\":false,\"same\":x,\"same\":{},\"same\":[]}");
}

// a NUL inside the key: the C driver NUL-splits the line and hands cJSON a char*, so the key truncates to `a` before add_item_to_object copies it (LESSONS #29 -- this has to hold at EVERY boundary, not just the printer)
#[test]
#[rustfmt::skip]
fn probe_construct_key_nul_truncates() {
    check("construct-key-nul-truncates", &["construct"], b"1\x09a\x00b\x09x\x0aabcd", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"a\":true,\"a\":false,\"a\":x,\"a\":{},\"a\":[]}");
}

// the same truncation for the raw text, via cJSON_strdup's strlen
#[test]
#[rustfmt::skip]
fn probe_construct_raw_nul_truncates() {
    check("construct-raw-nul-truncates", &["construct"], b"1\x09k\x09y\x00z\x0aabcd", 0, b"false=1;bool=2;raw=1:y;ints=0;flts=0;dbls=0;strs=1|4:abcd;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":y,\"k\":{},\"k\":[]}");
}

// no newline: rc 2, nothing on stdout, on both sides
#[test]
#[rustfmt::skip]
fn probe_construct_no_newline() {
    check("construct-no-newline", &["construct"], b"1\x09k\x09x", 2, b"");
}

// no tab at all: rc 2
#[test]
#[rustfmt::skip]
fn probe_construct_no_tab() {
    check("construct-no-tab", &["construct"], b"1 k x\x0apayload", 2, b"");
}

// only ONE tab: the raw field is missing, rc 2
#[test]
#[rustfmt::skip]
fn probe_construct_one_tab() {
    check("construct-one-tab", &["construct"], b"1\x09k\x0apayload", 2, b"");
}

// the same malformed header with a tab in the PAYLOAD: still rc 2, which proves the second-tab search is bounded by the newline rather than scanning the whole input
#[test]
#[rustfmt::skip]
fn probe_construct_tab_in_payload_doesnt_rescue() {
    check("construct-tab-in-payload-doesnt-rescue", &["construct"], b"1\x09k\x0apay\x09load", 2, b"");
}

// empty stdin: rc 2
#[test]
#[rustfmt::skip]
fn probe_construct_empty_input() {
    check("construct-empty-input", &["construct"], b"", 2, b"");
}

// 3 bytes: no whole int/float/double group, so those arrays are EMPTY -- but the pointer is non-NULL, so they are empty ARRAYS, not NULL. The string array still sees one field
#[test]
#[rustfmt::skip]
fn probe_construct_partial_group_3_bytes() {
    check("construct-partial-group-3-bytes", &["construct"], b"9\x09k\x09x\x0aabc", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=1|3:abc;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// 7 bytes: one whole int and one whole float, but no whole double -- a trailing partial group is DROPPED, never zero-padded
#[test]
#[rustfmt::skip]
fn probe_construct_partial_group_7_bytes() {
    check("construct-partial-group-7-bytes", &["construct"], b"9\x09k\x09x\x0aabcdefg", 0, b"false=1;bool=2;raw=1:x;ints=0;flts=0;dbls=0;strs=1|7:abcdefg;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// 20 whole ints against the 16-element cap: both sides must clamp to 16 identically. The cap bounds the descriptor; it is not a cJSON limit
#[test]
#[rustfmt::skip]
fn probe_construct_cap_20_elements() {
    check("construct-cap-20-elements", &["construct"], b"20\x09k\x09x\x0a\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00\x0a\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\x0d\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00", 0, b"false=1;bool=2;raw=1:x;ints=6|0,0000000000000000|1,3ff0000000000000|2,4000000000000000|3,4008000000000000|4,4010000000000000|5,4014000000000000;flts=7|0,36da000000000000|0,36dc000000000000|0,36de000000000000|0,36e0000000000000|0,36e1000000000000|0,36e2000000000000|0,36e3000000000000;dbls=3|0,0008000000070000|0,000a000000090000|0,000c0000000b0000;strs=16|0:|0:|0:|0:|1:\x01|0:|0:|1:\x02|0:|0:|1:\x03|0:|0:|1:\x04|0:|0:;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}

// bytes 0x80-0x8F, none of which is valid UTF-8 on its own -- this probe is why the matrix format needed `stdin_b64` (LESSONS #36); it cannot be spelled as a JSON string at all
#[test]
#[rustfmt::skip]
fn probe_construct_high_bytes() {
    check("construct-high-bytes", &["construct"], b"3\x09k\x09x\x0a\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f", 0, b"false=1;bool=2;raw=1:x;ints=1|-2088599168,c1df1f5fa0000000;flts=1|0,b9b1917140000000;dbls=0;strs=1|16:\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f;addT=1;addF=1;addR=1;addO=1;addA=1;obj={\"k\":true,\"k\":false,\"k\":x,\"k\":{},\"k\":[]}");
}
