// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: plumbing
// transcript fingerprint: sha256:193db0ab8ab3c2f00d30c23f061eda4874bbbce4d2b48cc11b161c1ea8532ee6

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// buffer-plumbing: does the C's ParseBuffer skip a leading UTF-8 BOM?
#[test]
#[rustfmt::skip]
fn probe_bom_utf8_leading() {
    check("bom-utf8-leading", &["print-unformatted"], b"\xef\xbb\xbf{}", 0, b"{}");
}

// buffer-plumbing: whitespace-only input — parse error, or something else?
#[test]
#[rustfmt::skip]
fn probe_whitespace_only() {
    check("whitespace-only", &["print-unformatted"], b"   \x09\x0d\x0a ", 1, b"");
}

// buffer-plumbing: empty buffer at offset 0
#[test]
#[rustfmt::skip]
fn probe_empty_input() {
    check("empty-input", &["print-unformatted"], b"", 1, b"");
}

// buffer-plumbing: whitespace either side of a valid value
#[test]
#[rustfmt::skip]
fn probe_leading_trailing_ws() {
    check("leading-trailing-ws", &["print-unformatted"], b"  \x0a\x09 [1,2]  \x0d\x0a ", 0, b"[1,2]");
}

// buffer-plumbing: does parse reject trailing garbage after a complete value, or stop at the value?
#[test]
#[rustfmt::skip]
fn probe_trailing_garbage() {
    check("trailing-garbage", &["print-unformatted"], b"[1] xyz", 0, b"[1]");
}

// buffer-plumbing: an embedded NUL mid-buffer (length-aware parse vs C-string assumptions)
#[test]
#[rustfmt::skip]
fn probe_nul_inside_buffer() {
    check("nul-inside-buffer", &["print-unformatted"], b"[1,\x002]", 0, b"[1,2]");
}

// alloc-node: a container node with no children, FORMATTED print
#[test]
#[rustfmt::skip]
fn probe_empty_array() {
    check("empty-array", &["print"], b"[]", 0, b"[]");
}

// alloc-node: empty object, formatted (child-list head is NULL)
#[test]
#[rustfmt::skip]
fn probe_empty_object() {
    check("empty-object", &["print"], b"{}", 0, b"{\x0a}");
}

// alloc-node: nested empty containers — node linkage without leaves
#[test]
#[rustfmt::skip]
fn probe_nested_empties() {
    check("nested-empties", &["print"], b"[[],{},[{}]]", 0, b"[[], {\x0a\x09}, [{\x0a\x09\x09}]]");
}

// alloc-node: a lone literal node, no allocation of children
#[test]
#[rustfmt::skip]
fn probe_bare_null() {
    check("bare-null", &["print-unformatted"], b"null", 0, b"null");
}

// alloc-node: Duplicate must reproduce empty-container linkage
#[test]
#[rustfmt::skip]
fn probe_dup_nested_empties() {
    check("dup-nested-empties", &["dup"], b"[[],{},[{}]]", 0, b"[[],{},[{}]]");
}
