// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-mutate-set
// transcript fingerprint: sha256:15d898933c006e9447f3057afcf9dde977c99cbf50df54dbe63da42bf49498ea

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// no such key: cJSON_SetValuestring's OWN `object == NULL` guard, and the one call the mode must skip (cJSON_SetNumberHelper has no NULL check at all -- sn=-)
#[test]
#[rustfmt::skip]
fn probe_set_no_target_missing_key() {
    check("set-no-target-missing-key", &["set"], b"3ff0000000000000\x09zz\x09x\x0a{\"n\":1}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={\"n\":1}");
}

// cJSON_GetObjectItemCaseSensitive on an ARRAY answers NULL, so the whole document path takes its no-target branch
#[test]
#[rustfmt::skip]
fn probe_set_no_target_root_array() {
    check("set-no-target-root-array", &["set"], b"3ff0000000000000\x09k\x09x\x0a[1,2,3]", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc=[1,2,3]");
}

// same for a scalar root -- the lookup has no child list to walk
#[test]
#[rustfmt::skip]
fn probe_set_no_target_root_scalar() {
    check("set-no-target-root-scalar", &["set"], b"3ff0000000000000\x09k\x09x\x0a\"top\"", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc=\"top\"");
}

// an unparseable document is NOT an error in this mode (rc=0, doc=-): the setters are the surface under test and must still run. Every other mode exits 1 here
#[test]
#[rustfmt::skip]
fn probe_set_doc_unparseable() {
    check("set-doc-unparseable", &["set"], b"3ff0000000000000\x09k\x09x\x0a{oops", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc=-");
}

// empty document: ParseWithLength(.., 0) fails, same no-target path
#[test]
#[rustfmt::skip]
fn probe_set_doc_empty() {
    check("set-doc-empty", &["set"], b"3ff0000000000000\x09k\x09x\x0a", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc=-");
}

// the ordinary path: a NUMBER target, so cJSON_SetValuestring refuses it (not a cJSON_String) and cJSON_SetNumberHelper owns it
#[test]
#[rustfmt::skip]
fn probe_set_number_target_in_range() {
    check("set-number-target-in-range", &["set"], b"4008000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i3,d4008000000000000,s-,p3;sv=-;sn=4008000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i3,d4008000000000000,s-,p3;sn2=4008000000000000;doc={\"n\":3}");
}

// setting 0 over an existing number, with an EMPTY replacement string
#[test]
#[rustfmt::skip]
fn probe_set_number_target_zero() {
    check("set-number-target-zero", &["set"], b"0000000000000000\x09n\x09\x0a{\"n\":42}", 0, b"tgt=t8,i0,d0000000000000000,s-,p0;sv=-;sn=0000000000000000;s2=t16,i0,d0000000000000000,s0:,p\"\";sv2=0:;svnull=-;svnum=-;n2=t8,i0,d0000000000000000,s-,p0;sn2=0000000000000000;doc={\"n\":0}");
}

// -0.0: valueint is 0 and the sign survives only in valuedouble's bits, which is why the descriptor carries bits rather than a formatted float
#[test]
#[rustfmt::skip]
fn probe_set_number_target_neg_zero() {
    check("set-number-target-neg-zero", &["set"], b"8000000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d8000000000000000,s-,p0;sv=-;sn=8000000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d8000000000000000,s-,p0;sn2=8000000000000000;doc={\"n\":0}");
}

// -7.5 truncates TOWARD ZERO into valueint (-7) while valuedouble stays exact
#[test]
#[rustfmt::skip]
fn probe_set_number_target_fraction() {
    check("set-number-target-fraction", &["set"], b"c01e000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i-7,dc01e000000000000,s-,p-7.5;sv=-;sn=c01e000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i-7,dc01e000000000000,s-,p-7.5;sn2=c01e000000000000;doc={\"n\":-7.5}");
}

// 3e9 > INT_MAX: the first saturation guard (cJSON.c:386)
#[test]
#[rustfmt::skip]
fn probe_set_number_target_saturate_high() {
    check("set-number-target-saturate-high", &["set"], b"41e65a0bc0000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483647,d41e65a0bc0000000,s-,p3000000000;sv=-;sn=41e65a0bc0000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483647,d41e65a0bc0000000,s-,p3000000000;sn2=41e65a0bc0000000;doc={\"n\":3000000000}");
}

// -3e9 < INT_MIN: the second saturation guard
#[test]
#[rustfmt::skip]
fn probe_set_number_target_saturate_low() {
    check("set-number-target-saturate-low", &["set"], b"c1e65a0bc0000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i-2147483648,dc1e65a0bc0000000,s-,p-3000000000;sv=-;sn=c1e65a0bc0000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i-2147483648,dc1e65a0bc0000000,s-,p-3000000000;sn2=c1e65a0bc0000000;doc={\"n\":-3000000000}");
}

// exactly INT_MAX as a double: `number >= INT_MAX` is TRUE, so it saturates rather than casting -- the boundary is inclusive
#[test]
#[rustfmt::skip]
fn probe_set_number_target_int_max() {
    check("set-number-target-int-max", &["set"], b"41dfffffffc00000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483647,d41dfffffffc00000,s-,p2147483647;sv=-;sn=41dfffffffc00000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483647,d41dfffffffc00000,s-,p2147483647;sn2=41dfffffffc00000;doc={\"n\":2147483647}");
}

// one representable step below: the cast branch, not the guard
#[test]
#[rustfmt::skip]
fn probe_set_number_target_int_max_minus_one() {
    check("set-number-target-int-max-minus-one", &["set"], b"41dfffffff800000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483646,d41dfffffff800000,s-,p2147483646;sv=-;sn=41dfffffff800000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483646,d41dfffffff800000,s-,p2147483646;sn2=41dfffffff800000;doc={\"n\":2147483646}");
}

// exactly INT_MIN as a double: `number <= (double)INT_MIN` is TRUE, also inclusive
#[test]
#[rustfmt::skip]
fn probe_set_number_target_int_min() {
    check("set-number-target-int-min", &["set"], b"c1e0000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i-2147483648,dc1e0000000000000,s-,p-2147483648;sv=-;sn=c1e0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i-2147483648,dc1e0000000000000,s-,p-2147483648;sn2=c1e0000000000000;doc={\"n\":-2147483648}");
}

// +inf saturates to INT_MAX and PRINTS as null (cJSON refuses to emit a non-finite number)
#[test]
#[rustfmt::skip]
fn probe_set_number_target_inf() {
    check("set-number-target-inf", &["set"], b"7ff0000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483647,d7ff0000000000000,s-,pnull;sv=-;sn=7ff0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483647,d7ff0000000000000,s-,pnull;sn2=7ff0000000000000;doc={\"n\":null}");
}

// -inf saturates to INT_MIN, prints null
#[test]
#[rustfmt::skip]
fn probe_set_number_target_neg_inf() {
    check("set-number-target-neg-inf", &["set"], b"fff0000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i-2147483648,dfff0000000000000,s-,pnull;sv=-;sn=fff0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i-2147483648,dfff0000000000000,s-,pnull;sn2=fff0000000000000;doc={\"n\":null}");
}

// 1e308: finite but far past INT_MAX; prints in full precision
#[test]
#[rustfmt::skip]
fn probe_set_number_target_huge() {
    check("set-number-target-huge", &["set"], b"7fe1ccf385ebc8a0\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483647,d7fe1ccf385ebc8a0,s-,p1e+308;sv=-;sn=7fe1ccf385ebc8a0;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483647,d7fe1ccf385ebc8a0,s-,p1e+308;sn2=7fe1ccf385ebc8a0;doc={\"n\":1e+308}");
}

// the smallest positive subnormal: valueint 0, valuedouble non-zero
#[test]
#[rustfmt::skip]
fn probe_set_number_target_subnormal() {
    check("set-number-target-subnormal", &["set"], b"0000000000000001\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d0000000000000001,s-,p4.94065645841247e-324;sv=-;sn=0000000000000001;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d0000000000000001,s-,p4.94065645841247e-324;sn2=0000000000000001;doc={\"n\":4.94065645841247e-324}");
}

// 0.5 truncates to 0 -- a number whose valueint and valuedouble disagree, which is what the printer's integer fast-path keys off
#[test]
#[rustfmt::skip]
fn probe_set_number_target_half() {
    check("set-number-target-half", &["set"], b"3fe0000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d3fe0000000000000,s-,p0.5;sv=-;sn=3fe0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d3fe0000000000000,s-,p0.5;sn2=3fe0000000000000;doc={\"n\":0.5}");
}

// duplicate keys: the C walks the child list and stops at the FIRST match, so only the first is set
#[test]
#[rustfmt::skip]
fn probe_set_dup_key_first_wins() {
    check("set-dup-key-first-wins", &["set"], b"4008000000000000\x09k\x09x\x0a{\"k\":1,\"k\":2}", 0, b"tgt=t8,i3,d4008000000000000,s-,p3;sv=-;sn=4008000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i3,d4008000000000000,s-,p3;sn2=4008000000000000;doc={\"k\":3,\"k\":2}");
}

// this mode uses cJSON_GetObjectItemCaseSensitive, so `k` does not find `K` -- no target
#[test]
#[rustfmt::skip]
fn probe_set_lookup_is_case_sensitive() {
    check("set-lookup-is-case-sensitive", &["set"], b"3ff0000000000000\x09k\x09x\x0a{\"K\":1}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={\"K\":1}");
}

// empty key AND empty replacement: s2 is CreateString(""), then set to "" -- strlen(new) <= strlen(old) with both zero
#[test]
#[rustfmt::skip]
fn probe_set_newstr_empty_on_empty_key() {
    check("set-newstr-empty-on-empty-key", &["set"], b"3ff0000000000000\x09\x09\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s0:,p\"\";sv2=0:;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// s2's old text is 1 byte and the new is 16: the ALLOCATING side of cJSON.c:416. Crossed, but not distinguishable from outside -- both paths leave the same valuestring
#[test]
#[rustfmt::skip]
fn probe_set_newstr_longer_than_key() {
    check("set-newstr-longer-than-key", &["set"], b"3ff0000000000000\x09k\x09abcdefghijklmnop\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s16:abcdefghijklmnop,p\"abcdefghijklmnop\";sv2=16:abcdefghijklmnop;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// the reverse: the in-place strcpy side of the same branch
#[test]
#[rustfmt::skip]
fn probe_set_newstr_shorter_than_key() {
    check("set-newstr-shorter-than-key", &["set"], b"3ff0000000000000\x09abcdefghij\x09z\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:z,p\"z\";sv2=1:z;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// exactly equal lengths -- `<=` makes this the in-place side, so the boundary is pinned
#[test]
#[rustfmt::skip]
fn probe_set_newstr_equal_length() {
    check("set-newstr-equal-length", &["set"], b"3ff0000000000000\x09abc\x09xyz\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s3:xyz,p\"xyz\";sv2=3:xyz;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// a replacement needing JSON escaping: the descriptor carries the RAW bytes (length-prefixed) and the printed form separately
#[test]
#[rustfmt::skip]
fn probe_set_newstr_escapes() {
    check("set-newstr-escapes", &["set"], b"3ff0000000000000\x09k\x09a\"b\\\\c\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s6:a\"b\\\\c,p\"a\\\"b\\\\\\\\c\";sv2=6:a\"b\\\\c;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// an interior NUL in the replacement: cJSON_SetValuestring takes a `const char *`, so it copies "ab" and the rest is gone (LESSONS #29). Needs stdin_b64 -- a JSON string cannot spell it (LESSONS #36)
#[test]
#[rustfmt::skip]
fn probe_set_newstr_interior_nul() {
    check("set-newstr-interior-nul", &["set"], b"3ff0000000000000\x09k\x09ab\x00cd\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s2:ab,p\"ab\";sv2=2:ab;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// an interior NUL in the KEY: the driver hands cJSON a C string, so the lookup is for `k` and it FINDS the target
#[test]
#[rustfmt::skip]
fn probe_set_key_interior_nul() {
    check("set-key-interior-nul", &["set"], b"3ff0000000000000\x09k\x00extra\x09x\x0a{\"k\":1}", 0, b"tgt=t8,i1,d3ff0000000000000,s-,p1;sv=-;sn=3ff0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={\"k\":1}");
}

// bytes 0x80-0xFF in the replacement: cJSON copies string content verbatim with no UTF-8 validation, and the printer emits them raw
#[test]
#[rustfmt::skip]
fn probe_set_newstr_high_bytes() {
    check("set-newstr-high-bytes", &["set"], b"3ff0000000000000\x09k\x09\xff\xfe\x80\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s3:\xff\xfe\x80,p\"\xff\xfe\x80\";sv2=3:\xff\xfe\x80;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// a control byte: printed as \u0001, so the raw bytes and the printed form differ
#[test]
#[rustfmt::skip]
fn probe_set_newstr_control_byte() {
    check("set-newstr-control-byte", &["set"], b"3ff0000000000000\x09k\x09a\x01b\x0a{}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s3:a\x01b,p\"a\\u0001b\";sv2=3:a\x01b;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={}");
}

// a PARSED string carrying an interior NUL, but NOT targeted: pins that the descriptor's byte fields are C-string fields (the `set` target here is absent)
#[test]
#[rustfmt::skip]
fn probe_set_target_string_with_interior_nul_no_write() {
    check("set-target-string-with-interior-nul-no-write", &["set"], b"3ff0000000000000\x09zz\x09x\x0a{\"k\":\"a\\u0000bcdef\"}", 0, b"tgt=-;sv=-;sn=-;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={\"k\":\"a\"}");
}

// a non-hex bits field reads as 0 on both sides before any double exists
#[test]
#[rustfmt::skip]
fn probe_set_bits_junk() {
    check("set-bits-junk", &["set"], b"zz\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d0000000000000000,s-,p0;sv=-;sn=0000000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d0000000000000000,s-,p0;sn2=0000000000000000;doc={\"n\":0}");
}

// an empty bits field is also 0 -- the field is optional in effect, never an error
#[test]
#[rustfmt::skip]
fn probe_set_bits_empty() {
    check("set-bits-empty", &["set"], b"\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d0000000000000000,s-,p0;sv=-;sn=0000000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d0000000000000000,s-,p0;sn2=0000000000000000;doc={\"n\":0}");
}

// uppercase hex digits are accepted, giving +inf
#[test]
#[rustfmt::skip]
fn probe_set_bits_uppercase() {
    check("set-bits-uppercase", &["set"], b"7FF0000000000000\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i2147483647,d7ff0000000000000,s-,pnull;sv=-;sn=7ff0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i2147483647,d7ff0000000000000,s-,pnull;sn2=7ff0000000000000;doc={\"n\":null}");
}

// 17 hex digits: only the first 16 are read, so the trailing nibble is ignored rather than shifting the value
#[test]
#[rustfmt::skip]
fn probe_set_bits_seventeen_digits() {
    check("set-bits-seventeen-digits", &["set"], b"3ff0000000000000f\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i1,d3ff0000000000000,s-,p1;sv=-;sn=3ff0000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i1,d3ff0000000000000,s-,p1;sn2=3ff0000000000000;doc={\"n\":1}");
}

// the scan stops at the first non-hex character, so this is 0x3ff0 -- a tiny subnormal, not 1.0
#[test]
#[rustfmt::skip]
fn probe_set_bits_trailing_junk() {
    check("set-bits-trailing-junk", &["set"], b"3ff0zzzz\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d0000000000003ff0,s-,p8.08686649112952e-320;sv=-;sn=0000000000003ff0;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d0000000000003ff0,s-,p8.08686649112952e-320;sn2=0000000000003ff0;doc={\"n\":8.08686649112952e-320}");
}

// a single digit: 0x8, the eighth subnormal
#[test]
#[rustfmt::skip]
fn probe_set_bits_short() {
    check("set-bits-short", &["set"], b"8\x09n\x09x\x0a{\"n\":1}", 0, b"tgt=t8,i0,d0000000000000008,s-,p3.95252516672997e-323;sv=-;sn=0000000000000008;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i0,d0000000000000008,s-,p3.95252516672997e-323;sn2=0000000000000008;doc={\"n\":3.95252516672997e-323}");
}

// a nested document, target at top level: the rest of the tree must come back unchanged in doc=
#[test]
#[rustfmt::skip]
fn probe_set_nested_number_target() {
    check("set-nested-number-target", &["set"], b"4008000000000000\x09n\x09x\x0a{\"a\":{\"b\":1},\"n\":7}", 0, b"tgt=t8,i3,d4008000000000000,s-,p3;sv=-;sn=4008000000000000;s2=t16,i0,d0000000000000000,s1:x,p\"x\";sv2=1:x;svnull=-;svnum=-;n2=t8,i3,d4008000000000000,s-,p3;sn2=4008000000000000;doc={\"a\":{\"b\":1},\"n\":3}");
}

// no newline: usage error, rc 2 with nothing on stdout
#[test]
#[rustfmt::skip]
fn probe_set_usage_no_newline() {
    check("set-usage-no-newline", &["set"], b"3ff0000000000000\x09k\x09x", 2, b"");
}

// only one tab: usage error
#[test]
#[rustfmt::skip]
fn probe_set_usage_one_tab() {
    check("set-usage-one-tab", &["set"], b"3ff0000000000000\x09k\x0a{}", 2, b"");
}

// no tabs at all: usage error
#[test]
#[rustfmt::skip]
fn probe_set_usage_no_tabs() {
    check("set-usage-no-tabs", &["set"], b"abc\x0a{}", 2, b"");
}

// the tabs must be in the HEAD line; one after the newline does not count
#[test]
#[rustfmt::skip]
fn probe_set_usage_tab_after_newline() {
    check("set-usage-tab-after-newline", &["set"], b"3ff0000000000000\x0a{}\x09k\x09x", 2, b"");
}
