// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: ffi-builder
// transcript fingerprint: sha256:0573395a691fa8130d906f11f77e3d353842cc6575dc62cfdd996ac644411f4e

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// builder: AddString/Number/Bool/Null to an object, in insertion order
#[test]
#[rustfmt::skip]
fn probe_build_flat() {
    check("build-flat", &["build"], b"flat", 0, b"{\"s\":\"hi\",\"n\":42,\"t\":true,\"f\":false,\"z\":null}");
}

// builder: AddItemToArray with Create Number/String/True/Null
#[test]
#[rustfmt::skip]
fn probe_build_array() {
    check("build-array", &["build"], b"array", 0, b"[1,\"two\",true,null]");
}

// builder: an object holding an array holding an object
#[test]
#[rustfmt::skip]
fn probe_build_nested() {
    check("build-nested", &["build"], b"nested", 0, b"{\"arr\":[{\"deep\":-1}]}");
}

// builder: CreateNumber edges -- 0, -1, 0.1, 1e308 and inf. inf prints as null, the same quirk the parse side has
#[test]
#[rustfmt::skip]
fn probe_build_numbers() {
    check("build-numbers", &["build"], b"numbers", 0, b"[0,-1,0.1,1e+308,null]");
}

// builder: adding the SAME key twice APPENDS, it does not replace -- the C silently produces a duplicate-key document (and such a doc never compares equal to its own duplicate, per LESSONS #17)
#[test]
#[rustfmt::skip]
fn probe_build_dupkey() {
    check("build-dupkey", &["build"], b"dupkey", 0, b"{\"k\":1,\"k\":2}");
}

// builder: AddItemToObject(obj, key, NULL) is SILENTLY IGNORED -- no error, no crash, the key simply does not appear
#[test]
#[rustfmt::skip]
fn probe_build_add_null() {
    check("build-add-null", &["build"], b"add-null", 0, b"{\"b\":1}");
}

// builder: an object with no members
#[test]
#[rustfmt::skip]
fn probe_build_empty() {
    check("build-empty", &["build"], b"empty", 0, b"{}");
}

// builder: CreateString escaping must match the printer's
#[test]
#[rustfmt::skip]
fn probe_build_strings() {
    check("build-strings", &["build"], b"strings", 0, b"[\"\",\"a\\\"b\\\\c\",\"tab\\there\"]");
}

// query: valuestring holds the RAW bytes; valueint is 0
#[test]
#[rustfmt::skip]
fn probe_query_string() {
    check("query-string", &["query"], b"a\x0a{\"a\":\"hi\"}", 0, b"is=S;type=16;int=0;str=hi;size=0;print=\"hi\"");
}

// query: valueint mirrors an integral number
#[test]
#[rustfmt::skip]
fn probe_query_int() {
    check("query-int", &["query"], b"a\x0a{\"a\":42}", 0, b"is=M;type=8;int=42;str=-;size=0;print=42");
}

// query: valueint TRUNCATES toward zero (-7.5 -> -7) while the printed form stays exact -- a caller reading ->valueint silently loses the fraction
#[test]
#[rustfmt::skip]
fn probe_query_frac() {
    check("query-frac", &["query"], b"a\x0a{\"a\":-7.5}", 0, b"is=M;type=8;int=-7;str=-;size=0;print=-7.5");
}

// query: IsTrue AND IsBool both answer true; type is cJSON_True(2), valueint 1
#[test]
#[rustfmt::skip]
fn probe_query_true() {
    check("query-true", &["query"], b"a\x0a{\"a\":true}", 0, b"is=TB;type=2;int=1;str=-;size=0;print=true");
}

// query: IsNull, type cJSON_NULL(4)
#[test]
#[rustfmt::skip]
fn probe_query_null() {
    check("query-null", &["query"], b"a\x0a{\"a\":null}", 0, b"is=N;type=4;int=0;str=-;size=0;print=null");
}

// query: IsArray, GetArraySize counts children
#[test]
#[rustfmt::skip]
fn probe_query_array() {
    check("query-array", &["query"], b"a\x0a{\"a\":[1,2,3]}", 0, b"is=A;type=32;int=0;str=-;size=3;print=[1,2,3]");
}

// query: IsObject, GetArraySize counts members
#[test]
#[rustfmt::skip]
fn probe_query_object() {
    check("query-object", &["query"], b"a\x0a{\"a\":{\"b\":1}}", 0, b"is=O;type=64;int=0;str=-;size=1;print={\"b\":1}");
}

// query: GetObjectItemCaseSensitive does NOT match a differently-cased key
#[test]
#[rustfmt::skip]
fn probe_query_case() {
    check("query-case", &["query"], b"A\x0a{\"a\":1}", 0, b"missing");
}

// query: a missing key yields NULL, not an error
#[test]
#[rustfmt::skip]
fn probe_query_absent() {
    check("query-absent", &["query"], b"zz\x0a{\"a\":1}", 0, b"missing");
}

// query: inf saturates valueint at INT_MAX and prints as null
#[test]
#[rustfmt::skip]
fn probe_query_inf() {
    check("query-inf", &["query"], b"a\x0a{\"a\":1e999}", 0, b"is=M;type=8;int=2147483647;str=-;size=0;print=null");
}

// query: valueint SATURATES at INT_MAX(2147483647) while the printed value is exact -- the struct-field int view is lossy above 2^31-1
#[test]
#[rustfmt::skip]
fn probe_query_bignum() {
    check("query-bignum", &["query"], b"a\x0a{\"a\":3000000000}", 0, b"is=M;type=8;int=2147483647;str=-;size=0;print=3000000000");
}
