// @generated by the porting kit's probe harness (harnesses/probe/probe.py gen).
// DO NOT EDIT. Every expectation below is the C oracle's OBSERVED
// behavior (probe-then-port, LESSONS #17/#21): to change one, change
// the probe and re-run `probe.py run` + `gen`. `probe.py verify`
// byte-compares this file against a fresh regeneration, so a hand
// edit here FAILS the gate instead of silently redefining the spec.
// module: dom-add-parent
// transcript fingerprint: sha256:aff1fa9724f40adfc6022ad6041549de1bdd00ec06131de93257726f34b40285

mod probe_glue;

#[rustfmt::skip]
fn check(id: &str, args: &[&str], stdin: &[u8], want_rc: i32, want_stdout: &[u8]) {
    let (rc, stdout) = probe_glue::run_probe(args, stdin);
    assert_eq!(
        (rc, stdout.as_slice()),
        (want_rc, want_stdout),
        "probe `{id}` diverges from the pinned C-oracle transcript (never hand-edit; re-probe)"
    );
}

// the well-formed case for AddItemToArray: an actual array. A run where this diverges is a port bug, not this class
#[test]
#[rustfmt::skip]
fn probe_parent_arr_add_item() {
    check("parent-arr-add-item", &["parent"], b"arr\x09a\x09k\x0a{}", 0, b"rc=1;print=4:[99];size=1;item0=99;pre=0/0;post=0/0;key=0/0;empty=0/0;dupsz=1;cmp=1;doc={}");
}

// same, with the op appending rather than starting the list
#[test]
#[rustfmt::skip]
fn probe_parent_arr_add_into_nonempty() {
    check("parent-arr-add-into-nonempty", &["parent"], b"arr\x09a\x09k\x0a[]", 0, b"rc=1;print=4:[99];size=1;item0=99;pre=0/0;post=0/0;key=0/0;empty=0/0;dupsz=1;cmp=1;doc=[]");
}

// AddItemToObject onto an actual object
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_object() {
    check("parent-obj-add-object", &["parent"], b"obj\x09o\x09k\x0a{}", 0, b"rc=1;print=25:{\"pre\":1,\"k\":99,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// AddItemToObjectCS onto an actual object: the C BORROWS the key instead of copying it, which the port cannot express (it owns every key) -- but the borrow is invisible through this descriptor, so the two still agree
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_cs() {
    check("parent-obj-add-cs", &["parent"], b"obj\x09ocs\x09k\x0a{}", 0, b"rc=1;print=25:{\"pre\":1,\"k\":99,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// the cJSON_Add*ToObject family, onto an object
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_true() {
    check("parent-obj-add-true", &["parent"], b"obj\x09t\x09k\x0a{}", 0, b"rc=1;print=27:{\"pre\":1,\"k\":true,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// same, false
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_false() {
    check("parent-obj-add-false", &["parent"], b"obj\x09f\x09k\x0a{}", 0, b"rc=1;print=28:{\"pre\":1,\"k\":false,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// same, null
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_null() {
    check("parent-obj-add-null", &["parent"], b"obj\x09z\x09k\x0a{}", 0, b"rc=1;print=27:{\"pre\":1,\"k\":null,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// same, number
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_number() {
    check("parent-obj-add-number", &["parent"], b"obj\x09m\x09k\x0a{}", 0, b"rc=1;print=24:{\"pre\":1,\"k\":5,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// same, string
#[test]
#[rustfmt::skip]
fn probe_parent_obj_add_string() {
    check("parent-obj-add-string", &["parent"], b"obj\x09s\x09k\x0a{}", 0, b"rc=1;print=26:{\"pre\":1,\"k\":\"v\",\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=1;doc={}");
}

// a member genuinely keyed "" IS findable by "" -- empty=1/1. The contrast with the NULL-keyed member (empty=0/0, matrix-only) is the whole reason the printed form cannot be trusted: both print as ""
#[test]
#[rustfmt::skip]
fn probe_parent_obj_empty_key() {
    check("parent-obj-empty-key", &["parent"], b"obj\x09o\x09\x0a{}", 0, b"rc=1;print=24:{\"pre\":1,\"\":99,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=1/1;dupsz=3;cmp=1;doc={}");
}

// re-adding the key the mode already inserted: cJSON appends rather than replacing, so the object carries `pre` twice
#[test]
#[rustfmt::skip]
fn probe_parent_obj_duplicate_key() {
    check("parent-obj-duplicate-key", &["parent"], b"obj\x09m\x09pre\x0a{}", 0, b"rc=1;print=26:{\"pre\":1,\"pre\":5,\"post\":2};size=3;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=3;cmp=0;doc={}");
}

// an unrecognised op is rc=-1 on both sides
#[test]
#[rustfmt::skip]
fn probe_parent_unknown_op() {
    check("parent-unknown-op", &["parent"], b"arr\x09zzz\x09k\x0a{}", 0, b"rc=-1;print=2:[];size=0;item0=-;pre=0/0;post=0/0;key=0/0;empty=0/0;dupsz=0;cmp=1;doc={}");
}

// kind=doc with nothing to parse: no target at all, rc=-1, everything `-`
#[test]
#[rustfmt::skip]
fn probe_parent_doc_unparseable() {
    check("parent-doc-unparseable", &["parent"], b"doc\x09a\x09k\x0anot json at all", 0, b"rc=-1;print=-;size=-1;item0=-;pre=0/0;post=0/0;key=0/0;empty=0/0;dupsz=-1;cmp=0;doc=-");
}

// kind=doc is how a FUZZER picks the target type; here it picks a container, so both sides agree
#[test]
#[rustfmt::skip]
fn probe_parent_doc_array() {
    check("parent-doc-array", &["parent"], b"doc\x09a\x09k\x0a[1,2]", 0, b"rc=1;print=8:[1,2,99];size=3;item0=1;pre=0/0;post=0/0;key=0/0;empty=0/0;dupsz=3;cmp=1;doc=[1,2,99]");
}

// same, an object document
#[test]
#[rustfmt::skip]
fn probe_parent_doc_object() {
    check("parent-doc-object", &["parent"], b"doc\x09o\x09k\x0a{\"x\":1}", 0, b"rc=1;print=31:{\"x\":1,\"pre\":1,\"k\":99,\"post\":2};size=4;item0=1;pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=4;cmp=1;doc={\"x\":1,\"pre\":1,\"k\":99,\"post\":2}");
}

// a document with structure, so the descriptor's doc= field carries something the add actually changed
#[test]
#[rustfmt::skip]
fn probe_parent_doc_object_nested() {
    check("parent-doc-object-nested", &["parent"], b"doc\x09m\x09deep\x0a{\"a\":{\"b\":1}}", 0, b"rc=1;print=39:{\"a\":{\"b\":1},\"pre\":1,\"deep\":5,\"post\":2};size=4;item0={\"b\":1};pre=1/1;post=1/1;key=1/1;empty=0/0;dupsz=4;cmp=1;doc={\"a\":{\"b\":1},\"pre\":1,\"deep\":5,\"post\":2}");
}
