#!/usr/bin/env python3
"""Emit `cJSON_fixed.c` — the vendored cJSON.c with ONE correction:
`cJSON_CreateNumber` no longer converts a NaN to `int`.

The defect (cJSON.c:2452-2476):

    if (num >= INT_MAX)            { item->valueint = INT_MAX; }
    else if (num <= (double)INT_MIN) { item->valueint = INT_MIN; }
    else                           { item->valueint = (int)num; }   /* <-- */

A NaN fails BOTH comparisons (every comparison with NaN is false), so it falls
into `(int)num`. Converting a NaN to an integer type is **undefined behavior**
(C17 6.3.1.4p1: the behavior is undefined if the truncated value cannot be
represented). It is not merely theoretical-but-stable, either: it is
architecture-dependent in practice. x86-64's `cvttsd2si` yields the "integer
indefinite" value INT_MIN; AArch64's `fcvtzs` saturates a NaN to 0. So the same
source, compiled from the same C, answers differently per target.

The port takes Rust's `as` cast, which is *defined* to saturate and to map NaN
to 0 — i.e. the port picks the defined answer, which happens to be the one the C
already gives on AArch64. DIVERGENCES.md `create-number-nan-valueint` records
that decision, and `matrix-construct.json` pins it against the PRISTINE oracle
so the divergence is asserted, not assumed.

Why a corrected reference has to exist (LESSONS #28, generalized from
cJSON_Utils.c to the library proper by LESSONS #36): the divergence class is
*predicate-defined* — every NaN payload triggers it, and 8 random bytes are a
NaN roughly once in 2048 — so differential FUZZING against the pristine oracle
would rediscover it endlessly and there is no finite set of fingerprints to pin.
Fuzzing therefore compares the port against THIS corrected C, where both sides
answer 0 and any finding is a REAL port bug.

Reachability, stated honestly: `parse_number` (cJSON.c:374) has the identical
cast but is NOT affected — its character whitelist is `0-9 + - e E .`, so
`strtod` can return an infinity but never a NaN. `cJSON_SetNumberHelper`
(cJSON.c:396) has the identical cast and IS affected; it belongs to the
mutation API, which is not ported yet, so it is deliberately NOT patched here.
Patching code no module exercises would add an unverified branch to the
reference — LESSONS #31, a control nothing invokes. When the mutation module
lands, it patches that site and pins it the same way.

The pristine vendored source is never modified; this file is generated
(gitignored) and used only to build the fuzz oracle.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "c", "cJSON.c")
OUT = os.path.join(HERE, "cJSON_fixed.c")

# The `num` parameter name is what distinguishes cJSON_CreateNumber's copy of
# this block from the two textually near-identical ones (parse_number and
# cJSON_SetNumberHelper both name it `number`). The occurrence count is asserted
# below rather than trusted, so a vendored-source bump that renames the
# parameter fails loudly instead of patching nothing.
PRISTINE = """\
        /* use saturation in case of overflow */
        if (num >= INT_MAX)
        {
            item->valueint = INT_MAX;
        }
        else if (num <= (double)INT_MIN)
        {
            item->valueint = INT_MIN;
        }
        else
        {
            item->valueint = (int)num;
        }
"""

FIXED = """\
        /* use saturation in case of overflow */
        if (num >= INT_MAX)
        {
            item->valueint = INT_MAX;
        }
        else if (num <= (double)INT_MIN)
        {
            item->valueint = INT_MIN;
        }
        else if (num != num)
        {
            /* fixed: NaN fails both comparisons above and would reach
             * (int)num, which is UNDEFINED BEHAVIOR (C17 6.3.1.4p1) and
             * architecture-dependent in practice: INT_MIN on x86-64,
             * 0 on AArch64. Answer 0, which is what Rust's defined
             * saturating cast gives and what AArch64 already gives. */
            item->valueint = 0;
        }
        else
        {
            item->valueint = (int)num;
        }
"""


def main():
    text = open(SRC, encoding="utf-8").read()
    # Count, don't just test membership: `replace(..., 1)` would silently patch
    # only the first of several matches and the oracle would look corrected
    # while the other sites still carried the defect.
    found = text.count(PRISTINE)
    if found != 1:
        print(
            f"error: expected exactly 1 cJSON_CreateNumber saturation block, "
            f"found {found} (did the vendored source change?) — update "
            f"make_fixed_core.py",
            file=sys.stderr,
        )
        return 1
    fixed = text.replace(PRISTINE, FIXED, 1)
    banner = (
        "/* GENERATED by make_fixed_core.py from the vendored cJSON.c — "
        "DO NOT EDIT.\n"
        " * The ONLY change is cJSON_CreateNumber's NaN->int conversion\n"
        " * (DIVERGENCES.md create-number-nan-valueint). */\n"
    )
    open(OUT, "w", encoding="utf-8").write(banner + fixed)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
