#!/usr/bin/env python3
"""Emit `cJSON_Utils_fixed.c` — the vendored cJSON_Utils.c with ONE correction:
`decode_pointer_inplace` decodes `~0`/`~1` per RFC 6901 (the pristine function
writes to the wrong offset and never copies non-escape bytes after an escape,
so a Patch child key like `a~1b` corrupts to `a~/`).

Why a corrected reference exists (LESSONS #28: a predicate-defined intentional
divergence breaks differential FUZZING against the pristine oracle). The port
FIXES this bug (DIVERGENCES.md `utils-tilde-*`), so `diff_run` against the
pristine C shows the ledgered divergence — that is the honest record of how the
port differs from *shipped* cJSON. But differential FUZZING rediscovers that
divergence class endlessly (any `~`-escaped child key), which is not a finite
set to pin. So the fuzzer compares the Rust port against THIS corrected C:
both decode correctly, so any fuzz finding is a REAL port bug, not the
intentional class. The pristine vendored source is never modified; this file is
generated (gitignored) and used only to build the fuzz oracle.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "c", "cJSON_Utils.c")
OUT = os.path.join(HERE, "cJSON_Utils_fixed.c")

PRISTINE = """\
    for (; *string; (void)decoded_string++, string++)
    {
        if (string[0] == '~')
        {
            if (string[1] == '0')
            {
                decoded_string[0] = '~';
            }
            else if (string[1] == '1')
            {
                decoded_string[1] = '/';
            }
            else
            {
                /* invalid escape sequence */
                return;
            }

            string++;
        }
    }
"""

FIXED = """\
    for (; *string; (void)decoded_string++, string++)
    {
        if (string[0] == '~')
        {
            if (string[1] == '0')
            {
                decoded_string[0] = '~';
            }
            else if (string[1] == '1')
            {
                decoded_string[0] = '/'; /* fixed: [0], not [1] */
            }
            else
            {
                /* invalid escape sequence */
                return;
            }

            string++;
        }
        else
        {
            decoded_string[0] = string[0]; /* fixed: copy non-escape bytes */
        }
    }
"""


def main():
    text = open(SRC, encoding="utf-8").read()
    if PRISTINE not in text:
        print("error: pristine decode_pointer_inplace body not found (did the "
              "vendored source change?) — update make_fixed_utils.py",
              file=sys.stderr)
        return 1
    fixed = text.replace(PRISTINE, FIXED, 1)
    banner = ("/* GENERATED by make_fixed_utils.py from the vendored "
              "cJSON_Utils.c — DO NOT EDIT.\n"
              " * The ONLY change is a correct decode_pointer_inplace "
              "(DIVERGENCES.md utils-tilde-*). */\n")
    open(OUT, "w", encoding="utf-8").write(banner + fixed)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
